### ISSUE TITLE
Add instructions for development

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1017]
At the moment, there is no obvious way for a developer who isn't familiar with the codebase to understand/infer that the `etstool.py` file is what they need to look at to understand how to setup the development environment and run the test suite.

It would be very useful to have a small section in the README file or a longer DEVELOP.rst file which provide information for developers on setting up the development environment, running flake8 and the test suite etc.

**Comment by kitchoi** [comment]
Agreed the README should at least refer to the existence of `etstool.py`.
Then there are some more instructions in the file itself (provided that one has found the file...):
https://github.com/enthought/traitsui/blob/6416e49cd707eca9a71736ea6ee9704d496deded/etstool.py#L12-L77

**Comment by mdickinson** [comment]
If you're making revisions to the README, bear in mind that (currently) the README contents are what appears on the PyPI landing page for TraitsUI: https://pypi.org/project/traitsui/

**Comment by mdickinson** [comment]
We may want to change the way that the long_description in the setup is based on the README, or maybe separate the README into two sections. Comments about etstool.py aren't going to be terribly useful to people on PyPI wondering  what TraitsUI does, or to people who've installed TraitsUI from PyPI.

**Comment by rahulporuri** [comment]
> We may want to change the way that the long_description in the setup is based on the README, or maybe separate the README into two sections.

Here's what numpy/scipy/pandas do :

https://github.com/numpy/numpy/blob/6ef5ec39cdfaf77aa4600ec2e3bf9f679a4fd527/setup.py#L444
https://github.com/scipy/scipy/blob/6bd8975294ec0d66d159195d3ffb50d336eb6410/setup.py#L531
https://github.com/pandas-dev/pandas/blob/7ae3098e3ae2ec9101a9627d2e28666de9c158b0/setup.py#L766

We can do something similar and hardcode the PyPI long description in the setup.py. I prefer this approach. Less complexity. We rarely if ever update the PyPI description but the README changes more frequently.

**Comment by mdickinson** [comment]
@rahulporuri Sounds fine to me. It does potentially duplicate information, though: it makes sense to me that what's in the long description is also in the README, so if you follow that path then you do need to keep the two aligned. And then what happens in practice is that the long description gets out of date, because no-one on the developer side ever looks at it.

To avoid the duplication, you could have an explicit separator in the README (e.g., `.. end_of_long_description`, which shouldn't get rendered by GitHub), and have the setup machinery parse everything up to that separator.

**Comment by mdickinson** [comment]
> it makes sense to me that what's in the long description is also in the README

It also makes sense to have the two entirely separate :shrug:

**Comment by rahulporuri** [comment]
> To avoid the duplication, you could have an explicit separator in the README (e.g., `.. end_of_long_description`, which shouldn't get rendered by GitHub), and have the setup machinery parse everything up to that separator.

I like that idea but i still prefer duplicating it.

>  And then what happens in practice is that the long description gets out of date, because no-one on the developer side ever looks at it.

I want to counter that by adding that as an item to the release checklist but then again, you can counter that by saying that we don't always stricltly adhere to the release checklist.

@kitchoi @corranwebster any comments/preference?

**Comment by mdickinson** [comment]
Yes, on reflection, keep things simple: just keep the two separate, even if that involves some duplication of information.

**Comment by kitchoi** [comment]
I don't have a strong preference. For the purpose of this issue, it is sufficient if the README references the `etstool.py` and says developers should read the docstring in that file, or reference some other files where more detailed descriptions can be found.  If it is only a short sentence, it is not too bad to have it visible on PyPI.
