### ISSUE TITLE
Change the window icon to something nicer in the demo application

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1028]
Quote from https://github.com/enthought/traitsui/pull/1023#issuecomment-661063039:

> nit : application icon is this weird people (?) icon at the moment, even though we are shipping the Enthought E icon, which is advertised as the icon to EDM GUI

![87946993-4206cf80-ca92-11ea-8699-bd0a05a815d8](https://user-images.githubusercontent.com/3673984/87961474-a5522b00-caad-11ea-8435-8b32b5d2df79.png)

**Comment by corranwebster** [comment]
This is probably a wider issue about branding:

- I'd suggest a Python icon, rather than an Enthought icon for open source apps.
- we might want to replace the people icon with a Python icon as the default.
- we have a Python icon somewhere in Pyface already (one of the examples, I think).
- there's also a two-linked circles icon which appears in some places.

**Comment by kitchoi** [comment]
Cool. On that topic, is it okay for the application title to be "Enthought Tool Suite"? (The name shown on the GUI window)

**Comment by kitchoi** [comment]
While we are at this, we should change the desktop shortcut icon as well (for eam).
https://github.com/enthought/traitsui/blob/4594aaa9430c64e96dbb1313b123739c22631473/ets-demo/etsdemo/info.py#L32

We might as well just replace the icon file.

**Comment by kitchoi** [comment]
From the [PSF Trademark Usage Policy](https://www.python.org/psf/trademarks/):

> We do not want these trademarks to be used:
- to refer to any other programming language
- in a way that is misleading or may imply association of unrelated modules, tools, documentation, or other resources with the Python programming language
- in ways that confuse the community as to whether the Python programming language is open source and free to use

> Uses that Never Require Approval
> All trademarks are subject to "nominative use rules" that allow use of the trademark to name the trademarked entity in a way that is minimal and does not imply a sponsorship relationship with the trademark holder.

Although the application is open-sourced, given it could be wrapped in commercial products, I am not convinced that the use of Python logo falls in the "Uses that Never Require Approval" category.

I would suggest we use a more generic icon.
