### ISSUE TITLE
Errors and Warnings in the Tutorial code snippets 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1036]
This issue is a fraction of issue #1027.  Specifically it addresses the errors and warnings that occur when running example code located in 
code snipperts - [https://github.com/enthought/traitsui/tree/master/docs/source/tutorials/code_snippets](url)

```
$ python event_loop_qt.py
Traceback (most recent call last):
  File "event_loop_qt.py", line 1, in <module>
    from pyface.qt.QtCore import QApplication
ImportError: cannot import name 'QApplication'
```

```
$ python event_loop_wx.py
event_loop_wx.py:11: wxPyDeprecationWarning: Using deprecated class PySimpleApp. Use :class:`App` instead.
  wx.PySimpleApp().MainLoop()
```

Additionally, the files event_loop.py seems to explicitly use wx, but from the docs it was my understanding that it was toolkit agnostic.  This may not be a problem, but I was confused.  

```
$ python interactive.py
Traceback (most recent call last):
  File "interactive.py", line 3, in <module>
    from traitsui import View, Item, ButtonEditor
ImportError: cannot import name 'View'
```
replacing `from traits import *` and `from traitsui import View, Item, ButtonEditor` with `from traits.api import * ` and `from traitsui.api import * ` solved this issue.  Should imports from traits/traitsui always be replace with traits.api/traitsui.api? 

```
 python mpl_figure_editor.py 
Traceback (most recent call last):
  File "mpl_figure_editor.py", line 12, in <module>
    from traitsui.wx.editor import Editor
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/wx/__init__.py", line 26, in <module>
    from . import toolkit
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/wx/toolkit.py", line 43, in <module>
    from .constants import WindowColor, screen_dx, screen_dy
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/wx/constants.py", line 79, in <module>
    scrollbar_dx = wx.SystemSettings.GetMetric(wx.SYS_VSCROLL_X)
wx._core.PyNoAppError: The wx.App object must be created first!
```

**Comment by aaronayres35** [comment]
@rahulporuri @kitchoi Any comments on the event_loop.py file using wx, or the traits/traitsui and traits.api/traitsui.api imports?

**Comment by kitchoi** [comment]
Thank you for reviewing these examples. They are all valid issues/comments.

> Additionally, the files event_loop.py seems to explicitly use wx, but from the docs it was my understanding that it was toolkit agnostic. 

I agree that does look like an error. The `wx` import should be replaced with `from pyface.api import GUI`. And then the `wx.App().MainLoop()` can be replaced with `GUI(). start_event_loop()`?

> Should imports from traits/traitsui always be replace with traits.api/traitsui.api?

Yes.
