### ISSUE TITLE
Discrepancies between Tutorial text and code in Repo

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1037]
There are occasions where the code blocks in the tutorial https://docs.enthought.com/traitsui/tutorials/index.html do not directly line up with their corresponding .py files located in 
code snipperts - https://github.com/enthought/traitsui/tree/master/docs/source/tutorials/code_snippets
(it is possible some of these may have been intentional)

Specifically code snippet 2 
```
from traits.api import *
from traitsui.api import *

class Camera(HasTraits):
    gain = Enum(1, 2, 3, )
    exposure = CInt(10, label="Exposure", )

class TextDisplay(HasTraits):
    string = String()

    view= View( Item('string', show_label=False, springy=True, style='custom' ))

class Container(HasTraits):
    camera = Instance(Camera)
    display = Instance(TextDisplay)

    view = View(
                Item('camera', style='custom', show_label=False, ),
                Item('display', style='custom', show_label=False, ),
            )

container = Container(camera=Camera(), display=TextDisplay())
container.configure_traits()
```
and container.py:
```
from traits.api import *
from traitsui.api import *

class Camera(HasTraits):
    """ Camera object """

    gain = Enum(1, 2, 3,
        desc="the gain index of the camera",
        label="gain", )

    exposure = CInt(10,
        desc="the exposure time, in ms",
        label="Exposure", )

class Display(HasTraits):
    string = String()

    view= View( Item('string', show_label=False, springy=True, style='custom' ))

class Container(HasTraits):
    camera = Instance(Camera, ())
    display = Instance(Display, ())

    view = View(
                Item('camera', style='custom', show_label=False, ),
                Item('display', style='custom', show_label=False, ),
               )

Container().configure_traits()
```

In code snippet 5 the imports are 
```
from traits.api import *
from traitsui.api import View, Item, ButtonEditor
```
and the last line is `Counter().configure_traits()`.  Whereas in interactive.py it is:
```
from traits import *
from pyface.api import GUI
from traitsui import View, Item, ButtonEditor
```
and 
```
Counter().edit_traits()
GUI().start_event_loop()
```
This interactive.py yields an error mentioned in issue #1036.  I assume it should be replaced by the code snippet code.  

Lastly, the imports of code snippet 7:
```
from threading import Thread
from time import sleep
from traits.api import *
from traitsui.api import View, Item, ButtonEditor
```
do not match traits_thread.py
```
from threading import Thread
from time import sleep
from traits.api import Button, HasTraits, Instance, Str
from traitsui.api import View, Item
```

As an aside, the names of the .py files are never explicitly mentioned in the tutorial, instead code blocks are simply labeled as "code snippet X".  It isn't difficult to identify the correct files, but a reference to the names, or changing the file names so that there is cleaner alignment might be nice.

Also, where is the code for the Putting it all together section located?  I did not see it in the repo and the link given in the tutorial results in a file not found error.

**Comment by kitchoi** [comment]
> Also, where is the code for the Putting it all together section located? I did not see it in the repo and the link given in the tutorial results in a file not found error.

Looks like the code in that section was simply written in-line in the documentation source: https://raw.githubusercontent.com/enthought/traitsui/master/docs/source/tutorials/traits_ui_scientific_app.rst

The link is an external link. If it is dead, it would be good to remove that.
