### ISSUE TITLE
PNG icons aren't supported as desktop shortcut icons by edm/eam

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1042]
The etsdemo explicitly sets an icon - which is used in the EDM GUI application and by the edm/eam machinery to create the shortcut. See https://github.com/enthought/traitsui/blob/5e9043f51818256879f08cf98c3785f67a09f2c0/ets-demo/etsdemo/info.py#L28-L33

From the looks of it, windows shortcuts might not accept a PNG file, which is what we are defining as the icon at the moment. This causes the desktop shortcut icon to look blank/white. See below.

The fix here is to contribute an icon file in a file format that is acceptable on windows (along with mac os and linux) e.g. an ico file. I tested locally with a bmp file (24 bit bitmap to be specific) which worked on windows 10.

NOTE : Double-clicking the icon still does what we expect it to - it launches the application.

![broken-desktop-shortcut](https://user-images.githubusercontent.com/1926457/88046714-ff033580-cb3f-11ea-845f-239622317d00.PNG)

**Comment by kitchoi** [comment]
Note that we might want to use a Python icon instead. See #1028

**Comment by kitchoi** [comment]
Actually on second thought, we might want to remove the desktop shortcut.
Most installers allow the users to choose whether they want to set up a desktop shortcut...

**Comment by kitchoi** [comment]
Closed via #1043
