### ISSUE TITLE
Warnings in Demo code docstrings

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1065]
Many of the etc-demo code examples (found here  https://github.com/enthought/traitsui/tree/master/traitsui/examples/demo) contain a warning in their doctoring that the example may not work correctly.  
e.g
"
**WARNING**

  This demo might not work as expected and some documented features might be
  missing.

-------------------------------------------------------------------------------
"

In many cases though, these examples seem to have been fixed and are working properly.  These warnings should be removed.

**Comment by kitchoi** [comment]
Just a note: These comments are added quite recently actually, in the last month or so. So it might be worth checking out the PRs that added these comments to understand the motivations. If you feel that the statements could be changed or be more specific, please feel free to make those changes!

**Comment by aaronayres35** [comment]
> Just a note: These comments are added quite recently actually, in the last month or so. So it might be worth checking out the PRs that added these comments to understand the motivations. If you feel that the statements could be changed or be more specific, please feel free to make those changes!

Sounds good, will do.  Yes I am realizing now, in many cases I was mistaken.
