### ISSUE TITLE
Qt InstanceEditor initially appears as if the first item is selected despite the value being None

### ISSUE THREAD

**Issue by ffishburn** [enthought/traitsui#1134]
The Qt custom `InstanceEditor` initially appears as if the first item is selected, however the selection is not actually made (the underlying value is `None`). Expected behavior is for the combo box to appear empty until a selection is made, which is what `EnumEditor` does.

**Comment by corranwebster** [comment]
I'm assuming that this is when using the `name` or `values` option in the editor?

**Comment by ffishburn** [comment]
I observed it while using the `name` option. Here is a minimal example:

```Python
from traits.api import HasStrictTraits, Instance, List, Str
from traitsui.api import EnumEditor, InstanceEditor, Item, VGroup, View


class Option(HasStrictTraits):
    name = Str()


class Model(HasStrictTraits):
    selected_option = Instance(Option)
    all_options = List(Instance(Option))

    selected_name = Str()
    all_names = List(Str)

    view = View(
        VGroup(
            Item('selected_option', label='InstanceEditor',
                 editor=InstanceEditor(name='all_options', editable=False)),
            Item('selected_name', label='EnumEditor',
                 editor=EnumEditor(name='all_names')),
        ),
    )


if __name__ == "__main__":
    model = Model(
        all_options=[Option(name='Option A'), Option(name='Option B')],
        all_names=['Option A', 'Option B'],
    )
    model.configure_traits()
    print(f'Selected option: {model.selected_option}')
    print(f'Selected name: {model.selected_name}')
```

Here is the result:
![bug-demo](https://user-images.githubusercontent.com/48447032/89902921-a8bc6c00-dbac-11ea-8f9d-a4ad8c33bafa.png)

It looks to me like the issue can be fixed by modifying `update_editor` to set `choice.setCurrentIndex(-1)` when `item` is `None`
