### ISSUE TITLE
UI Tester key sequence delay mismatch between Wx and Qt

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1200]
The current Qt implementation adds the delay to each typed character, whereas on wx/OSX there is a delay and then all the text is written at once.  This is fine for the purposes of most tests, but when using the delay parameter, ideally a user wants to see interactions occurring as if it were a user interacting with the UI.

**Comment by kitchoi** [comment]
I guess this is referring to this block:
https://github.com/enthought/traitsui/blob/81902cc48f0af498d4f0f1a980dc8074da4d8265/traitsui/testing/tester/wx/helpers.py#L162-L164

There is a delay, the interaction is indeed slower, and the underlying text value is updated per-character. However on OSX, the view is not repainted per character.

**Comment by kitchoi** [comment]
> There is a delay, the interaction is indeed slower, and the underlying text value is updated per-character. However on OSX, the view is not repainted per character.

That observation is based on adding `delay=1000` to `UITester` in the following test, on wx and OSX:
https://github.com/enthought/traitsui/blob/d49711f03dea4ded35eb3caa4f045ee35cfa4223/traitsui/tests/editors/test_text_editor.py#L165-L176

**Comment by aaronayres35** [comment]
> I guess this is referring to this block:
> https://github.com/enthought/traitsui/blob/81902cc48f0af498d4f0f1a980dc8074da4d8265/traitsui/testing/tester/wx/helpers.py#L162-L164
> 
> There is a delay, the interaction is indeed slower, and the underlying text value is updated per-character. However on OSX, the view is not repainted per character.

Ah, I was being dumb - I will update the issue description!

**Comment by kitchoi** [comment]
I think this issue is about visual inspection when `delay` is set to a nonzero value. The implementation between wx and Qt is in fact consistent. The underlying trait is still updated per keystroke. I could not see an obvious way to fix this, but at the time, it does not affect the intended test logic, so this might to have to be tolerated under the context of testing.

**Comment by kitchoi** [comment]
>  I could not see an obvious way to fix this

Aha, I think I find a fix for that... PR coming :D
