### ISSUE TITLE
Add delay method to UITester/UIWrapper

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1202]
The current default behavior is that the delay is imposed before the action.  So, if I set my tester's delay to be 500 ms, and I try to observe what my test is doing, the last action the tests performed is often instantaneous and hard to see.  This could be resolved by moving delays after the action is performed.  However, it could also be solved by adding a delay method to UITester/UIWrapper, and this delay method could be useful more generally.
The idea would be do just call .delay() on the Tester/Wrapper and the test would basically just sleep for tester.delay or wrapper.delay ms (could easily add functionality to take in an optional argument of delay if you want the pause to be different from the tester/wrapper's delay attribute.

**Comment by kitchoi** [comment]
I guess this end-of-test delay is to be added momentarily for debugging purposes, i.e. they will be removed as soon as the developer is happy with the test? In that case there are multiple ways to achieve this: `import time; time.sleep(...)`, or perform an action such as a mouse click that is inconsequent for the context. Maybe we don't need to add a method on UITester or UIWrapper just for that?

**Comment by aaronayres35** [comment]
> I guess this end-of-test delay is to be added momentarily for debugging purposes, i.e. they will be removed as soon as the developer is happy with the test? In that case there are multiple ways to achieve this: `import time; time.sleep(...)`, or perform an action such as a mouse click that is inconsequential for the context. Maybe we don't need to add a method on UITester or UIWrapper just for that?

Yeah, the motivation for this issue was I found myself needing to call time.sleep() a lot while trying to write the demo examples.  However I guess I do agree, it is probably overkill to add it as a method to UITester/UIWrapper

**Comment by aaronayres35** [comment]
Closing as this probably just isn't worth it to add currently.  See comments above - one could just use time.sleep to get the same effect.
