### ISSUE TITLE
TabularEditor doesn't refresh instantly upon appending an element to a list trait contained in the trait being displayed

### ISSUE THREAD

**Issue by xamcost** [enthought/traitsui#1245]
Hi there ! It seems that `TabularEditor` doesn't refresh instantly if the trait it renders contains a list trait to which we append elements, as shown on this video:

![refres_append](https://user-images.githubusercontent.com/24434420/93757706-225d6600-fbff-11ea-9fa1-167acf7ea473.gif)

The video has been made using the following code snippet on python 3.6.10, traits 6.1, traitsui 7.0 and pyqt5 (5.14):

```Python3
from traits.api import (
    Button, HasTraits, Instance, List, Property, Str
)
from traitsui.api import (
    TabularAdapter, TabularEditor, UItem, View
)


class Foo(HasTraits):

    mylist = List(Str)


class FooAdapter(TabularAdapter):

    columns = [
        ('Name', 'name')
    ]

    name_content = Property(Str)

    def _get_name_content(self):
        return ', '.join(self.item.mylist)


class Bar(HasTraits):

    foo_list = List(Instance(Foo))

    selected = Instance(Foo)

    button = Button('Add')

    def default_traits_view(self):
        return View(
            UItem('button'),
            UItem(
                "foo_list",
                editor=TabularEditor(
                    adapter=FooAdapter(),
                    selected='selected',
                ),
            ),
            resizable=True,
        )

    def _button_fired(self):
        if self.selected is not None:
            self.selected.mylist.append('new')


if __name__ == "__main__":
    win = Bar(
        foo_list=[
            Foo(mylist=['test1']),
            Foo(mylist=['test2']),
        ]
    )
    win.configure_traits()

```

**Comment by corranwebster** [comment]
This is expected, as the `TabularEditor` doesn't know that it is using a list as opposed to some other data structure (eg. an array).  As a result, you need to manually trigger either a `refresh` or an `update`, depending on the change (replacing an element probably only needs a `refresh`, for example).  There is also the `auto_update` flag which tries to handle list updates correctly:

https://github.com/enthought/traitsui/blob/8e5559f91abed906a091169294548d5ca4ddd97d/traitsui/editors/tabular_editor.py#L47-L60

**Comment by xamcost** [comment]
Unfortunately I already tried to define an `Event`, pass it to `TabularEditor.update` or `TabularEditor.refresh`, and fire it in my function that update the list trait in one of the element of the trait rendered by `TabularEditor`, and it still doesn't work...

**Comment by xamcost** [comment]
But thanks for your prompt reply !

**Comment by corranwebster** [comment]
Can you add your use of `updated` to the example in the bug report, otherwise we can't diagnose what might be happening.

**Comment by xamcost** [comment]
Sure. Here is an updated snippet using `TabularEditor.update`. Note that passing that indicating `Bar.update_event` to `TabularEditor.refresh` doesn't work either. I also tried to set `TabularEditor.auto_update` to `True`, without success.

```Python3
from traits.api import (
    Button, Event, HasTraits, Instance, List, Property, Str
)
from traitsui.api import (
    TabularAdapter, TabularEditor, UItem, View
)


class Foo(HasTraits):

    mylist = List(Str)


class FooAdapter(TabularAdapter):

    columns = [
        ('Name', 'name')
    ]

    name_content = Property(Str)

    def _get_name_content(self):
        return ', '.join(self.item.mylist)


class Bar(HasTraits):

    foo_list = List(Instance(Foo))

    selected = Instance(Foo)

    update_event = Event()

    button = Button('Add')

    def default_traits_view(self):
        return View(
            UItem('button'),
            UItem(
                "foo_list",
                editor=TabularEditor(
                    adapter=FooAdapter(),
                    selected='selected',
                    update='update_event',
                ),
            ),
            resizable=True,
        )

    def _button_fired(self):
        if self.selected is not None:
            self.selected.mylist.append('new')
            self.update_event = True


if __name__ == "__main__":
    win = Bar(
        foo_list=[
            Foo(mylist=['test1']),
            Foo(mylist=['test2']),
        ]
    )
    win.configure_traits()
```

**Comment by xamcost** [comment]
That's not a solution, but invoking `pyface.api.GUI.process_events()` in `Bar._button_fired()` resolves the problem in the aforementioned specific case. That said, it doesn't resolve it in my context... but I did not manage to reproduce the case in a minimal way so far. I will keep you posted.
