### ISSUE TITLE
Corruption when traitsui specifies font with wx - ipython, OSX 

### ISSUE THREAD

**Issue by jdmarch** [enthought/traitsui#13]
Example: NumPy_array_view_editor_demo.py
font = 'Arial 8' works in Windows and Ubuntu, but in OSX fails with:
TraitError: The 'font' trait of an ArrayViewEditor instance must be a font descriptor string, but a value of "'Arial 8'" <&lt;type 'str'&gt; was specified.

8 point Arial is a valid font on the system.

[details below]

**Comment by corranwebster** [comment]
This appears to no longer be an issue?  I can't replicate any more.
