### ISSUE TITLE
Use "viewcode" Sphinx extension in documentation.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#1398]
I've found it really helpful to have direct links from the documentation to the source in many cases. We're already doing this for some ETS packages, but not others.

Could we add the source links for TraitsUI and Pyface? This should be as easy as adding `"sphinx.ext.viewcode"` to the list of Sphinx extensions in the `conf.py` configuration file.

**Comment by rahulporuri** [comment]
handled in https://github.com/enthought/traitsui/pull/1443
