### ISSUE TITLE
Rearrange panes in etsdemo application

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1439]
The etsdemo application always looks empty at the moment - and that is mainly because most of the visual space is taken up by the vertical middle pane (or tab) in the application which provides a human readable description. In most cases, this human readable description is a few lines long so the rest of the vertical space is just empty. On the other hand, the top-right pane which displays the code for the demo is almost always crowded and requires vertical scrolling to be able to read the relevant code.

Instead of the current layout, I propose swapping the human readable description pane with the code pane.

![etsdemo-app-layout](https://user-images.githubusercontent.com/1926457/101880448-d92c0b00-3b8a-11eb-85ce-097c0c15d659.png)

**Comment by corranwebster** [comment]
No - the solution is more content in the human readable bit.  If we do this, it will make the Traits tutorial look really bad.

Either that, or we have multiple different content types with different layouts (also possible, but more engineering in the demo system).

**Comment by rahulporuri** [comment]
> No - the solution is more content in the human readable bit.

Closing.

> Either that, or we have multiple different content types with different layouts (also possible, but more engineering in the demo system).

I don't think we have the time to work on this at the moment - and i'm not sure how much of an impact it will have even if we spent time on it.
