### ISSUE TITLE
InstanceChoiceItem should be an ABCHasStrictTraits

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#1480]
The `InstanceChoiceItem` class has several key methods which raise `NotImplementedError`.  As a result it should never be instantiated, and subclasses need to implement those methods, which is exactly the use case for Python ABCs and `@abstractmethod` decorators.

Implementing these would reduce errors from people implementing their own custom subclasses.

**Comment by DiddiLeija** [comment]
Hello @corranwebster, how is this issue going? If no one has fixed it yet, I would like to take it. Just tell me what do I have to do.

**Comment by rahulporuri** [comment]
Hey @DiddiLeija . None of us at Enthought are working on it at the moment as far as I know so feel free to assign it to yourself and work on it.

**Comment by DiddiLeija** [comment]
Ok. I can't self-assign issues here, but I can open a PR later.

**Comment by DiddiLeija** [comment]
Hello, I have a question. Do you want me to convert `InstanceChoiceItem` into an instance of `ABCHasStrictTraits`, or also to add decorators on the methods raising `NotImplementedError`?

**Comment by rahulporuri** [comment]
> Do you want me to convert `InstanceChoiceItem` into an instance of `ABCHasStrictTraits`, or also to add decorators on the methods raising `NotImplementedError`?

Both. In fact, once you decorate the methods with `abc.abstractmethod`, you can remove the `NotImplementedError` code from the methods.

**Comment by DiddiLeija** [comment]
@rahulporuri I created #1738, which may close this issue. Could you check it and give me a review?
