### ISSUE TITLE
Should InstanceEditor propagate its created ui's errors to the parent UI

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1501]
Basically if you have a view for some `HasTraits` class `A` with an instance editor that displays some nested ui for an instance of object `B`, then errors originating in that nested ui are not counted towards the errors of the ui for the object `A`.  This leads to problems such as an OK button for `A` being enabled even if there is invalid data entered for some of B's traits.

Here is an example:
```
from traits.api import HasTraits, String, Instance
from traitsui.api import  InstanceEditor, Item, View, UCustom
from traitsui.testing.api import (
    IsEnabled, KeyClick, KeySequence, MouseClick, TargetByName, UITester
)


class SomeClass(HasTraits):
    some_string = String("A", maxlen=3)

    traits_view = View(Item('some_string'))


class WrapperClass(HasTraits):
    something = Instance(SomeClass, args=())

    traits_view = View(
        Item(
            'something',
            editor=InstanceEditor(),
            style='custom'
        ),
        buttons=["OK", "Cancel"],
    )


if __name__ == '__main__':
    example = WrapperClass()
    tester = UITester()
    with tester.create_ui(example) as ui:
        something_ui = tester.find_by_name(ui, "something")
        some_string_field = something_ui.locate(TargetByName('some_string'))
        some_string_field.perform(KeySequence("abcd"))
        some_string_field.perform(KeyClick("Enter"))

        ok_button = tester.find_by_id(ui, "OK")
        print("OK button is enabled? :", ok_button.inspect(IsEnabled()))
        print("InstanceEditor UI: ", something_ui._target._ui)
        print("InstanceEditor UI's parent: ", something_ui._target._ui.parent)
        print("Main UI: ", ui)
        print("InstanceEditor UI Errors: ", something_ui._target._ui.errors)
        print("Main UI Errors: ", ui.errors)
```

Running this script gives:
```
OK button is enabled? : True
InstanceEditor UI:  <traitsui.ui.UI object at 0x7f99251b3468>
InstanceEditor UI's parent:  <traitsui.ui.UI object at 0x7f9925075200>
Main UI:  <traitsui.ui.UI object at 0x7f9925075200>
InstanceEditor UI Errors:  1
Main UI Errors:  0
```

Should the nested UI errors contribute to the errors count for the main UI?  Intuitively it seems like they should.  Is this the expected behavior, or is this a bug?

**Comment by rahulporuri** [comment]
@corranwebster do you have any comments regarding this issue?

**Comment by aaronayres35** [comment]
Offline Discussion: This is indeed a bug.  Simply put, if a nested UI has a field come up as red (invalid), the full ui should not let you click ok.

**Comment by aaronayres35** [comment]
FWIW adding the following few lines of code to the `traitsui.ui.UI` class seems to "fix" this issue.  This may be breaking existing code / or creating other problems and we would need to investigate.

```
    @on_trait_change("errors")
    def some_handler_name(self, object, name, old, new):
        if self.parent:
            self.parent.errors = self.parent.errors - old + new
```

Note the need to do `- old + new` so that we don't over count.  any time this UIs errors change, that change is factored in to the parent UI's errors.
