### ISSUE TITLE
Expose `clearButtonEnabled` for Qt TextEditor

### ISSUE THREAD

**Issue by pedrorivotti** [enthought/traitsui#1514]
Since Qt 5.2, there is a property in `QLineEdit` that allows enabling a button for clearing the contents of the widget.

![Screenshot 2021-02-08 at 11 53 07](https://user-images.githubusercontent.com/44579232/107216142-39f98780-6a04-11eb-856e-eeba652c29f8.png)

Would it be possible to expose a flag for enabling this at the `traitsui` `TextEditor` level?
I haven't found an equivalent for the wx backend.

Here is a link to the relevant section of the Qt docs:
https://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop

**Comment by corranwebster** [comment]
The looks to be a special-case of a general feature which allows attaching actions to a region inside a QLineEdit.  It may make sense to implement the general feature.

There is also a question as to whether a `SearchEditor` might match the use-case better.

**Comment by pedrorivotti** [comment]
Thanks @corranwebster for pointing out the `SearchEditor`. It seems like it would fit the use-case very well, but the relevant toggles (`search_button` and `cancel_button`) seem to only be implemented for the wx backend. If those were available for the Qt backend, that would be a good solution.
