### ISSUE TITLE
EnumEditor expanding in both directions when resizable and readonly

### ISSUE THREAD

**Issue by robertopreste** [enthought/traitsui#1528]
When setting `resizable=True` and `style="readonly"` to an item shown using an `EnumEditor`, it will expand both horizontally and vertically, taking all available space.

A simple example:

```python
from traits.api import Enum, HasTraits, Str
from traitsui.api import Item, VGroup, View

class MyView(HasTraits):

    item_1 = Str("An item")
    menu = Enum("first", "second")
    item_2 = Str("Another item")

    def default_traits_view(self):
        return View(
            VGroup(
                Item("item_1"),
                Item("menu",
                     resizable=True, 
                     style="readonly",  # culprit line
                ),
                Item("item_2"),
            ),
            height=500,
            width=500,
        )


if __name__ == '__main__':
    view = MyView()
    view.configure_traits()
```

Without `style="readonly"` (expected behaviour):
<img width="612" alt="Screenshot 2021-03-01 at 15 20 37" src="https://user-images.githubusercontent.com/16542755/109518020-cba76280-7aa1-11eb-9f81-61d62c45a81a.png">

With `style="readonly"` (unexpected behaviour):
<img width="612" alt="Screenshot 2021-03-01 at 15 20 55" src="https://user-images.githubusercontent.com/16542755/109518108-e083f600-7aa1-11eb-9285-5917f447477d.png">

**Comment by rahulporuri** [comment]
Thanks @robertopreste for the bug report. I am able to reproduce this on Windows with TraitsUI 7.1.1 and PyQt5/Qt5 5.14.2/5.12.6.
