### ISSUE TITLE
File / FileEditor no history (`entries` option not working)

### ISSUE THREAD

**Issue by mo-han** [enthought/traitsui#1530]
```python
class Test(HasTraits):
    p = File(entries=10, dialog_style='open')
```
```python
class Test(HasTraits):
    p = File(editor=FileEditor(entries=10, dialog_style='open'))
```

Neither shows the history combo box with `entries=10` provided.
Then found out the source code of `traitsui.editors.file_editor.FileEditor` says:
```python
    #: FIXME: add support
    entries = Int(10)
```
So does this mean `entries` option is actually not supported yet? Then why does the official document shows examples of `FileEditor` with history combo box?

**Comment by aaronayres35** [comment]
It looks as though this functionality is supported on the wx backend, but not for qt (hence the example shown in the documentation).
See:
https://github.com/enthought/traitsui/blob/974bbdab83823230da7ec6e8fd730be038576f57/traitsui/wx/file_editor.py#L62-L67
The fact that this is currently a wx specific feature is not at all clear currently and this is a problem.  It should be stated in the documentation that currently this feature is only available on wx, as well as in the comment in the source code.
Ultimately we want this functionality on qt as well, but in the mean time it needs to be clearly documented that it is not supported 

Also, slightly orthogonal to this issue, the History_demo which showcases this feature is currently broken on wx.  Fix coming soon.
