### ISSUE TITLE
RGBColor does not correctly convert hexadecimal integer to a tuple of floats

### ISSUE THREAD

**Issue by mswiggers** [enthought/traitsui#1531]
When I input an integer in 0xRRGGBB format to the RGBColor trait, I get the following error:

`... , line 59, in convert_to_color
    ((num / 0x100) & 0xFF) / 255.0,
TypeError: unsupported operand type(s) for &: 'float' and 'int'`

I'm still using TraitsUI 7.0.1, but I think the issue is still relevant. I think this is due to Python converting the result of the first division to a float, and this might be solved by replacing the normal division by an integer division (`//`):

https://github.com/enthought/traitsui/blob/bffbb3b518c57ac1a4178b60b942f0f6a9831cd2/traitsui/null/rgb_color_trait.py#L52

**Comment by corranwebster** [comment]
Yes, it looks like this was masked by the bug fixed in #707 until recently.  It also occurs in the Wx and Qt versions of this.

In fact, the fix to this should probably involve unifying the three copies of that function into one utility method stored somewhere!
