### ISSUE TITLE
The scroll-to-hint default behaviour of TabularEditor is uncommon and difficult to change (ambiguous attribute name)

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/traitsui#1534]
### Original issue description

Title **"TabularEditor centers the selected cell in view. There is no (clear) way to disable this."**

In a TabularEditor, when the user selects a cell (and the previous click was not done on the same *column*), then the table is redrawn to bring the cell closer to the middle of the frame. This happens even if the cell was already entirely in frame.

![Peek 2021-03-11 17-41](https://user-images.githubusercontent.com/7642150/110830427-1c347200-8291-11eb-8efc-74f3f2e55bb1.gif)
<details>

<summary> MWE source </summary>

```python
from traits.api import HasTraits, Str, List
from traitsui.api import TabularEditor, TabularAdapter, View, UItem

class DataItem(HasTraits):
    a = Str("a")
    b = Str("a")
    c = Str("a")
    d = Str("a")
    e = Str("a")

class AView(HasTraits):
    data = List()

    def _data_default(self):
        return [DataItem()] * 20

    def default_traits_view(self):
        return View(
            UItem(
                "data",
                editor=TabularEditor(
                    adapter=AnAdapter(),
                    editable=False,
                    show_row_titles=True,
                ),
            ), resizable=True, width=400,
        )

class AnAdapter(TabularAdapter):
    columns = [(ch*20, ch) for ch in "abcde"]

AView().configure_traits()
```

</details>

I would like to be able to disable this behavior. It doesn't play nicely with, for instance, double clicks (the table moves between the first and the second click<sup>[.](https://en.wikipedia.org/wiki/Whac-A-Mole)</sup>). It's also pretty uncommon among tabular UIs in the wild.

<details>

<summary> Example </summary>

![Peek 2021-03-11 18-10](https://user-images.githubusercontent.com/7642150/110834213-2e181400-8295-11eb-8760-ba643260ec95.gif)
LibreOffice Calc moves the view just enough to reveal a partially visible cell (with some padding).
Does nothing on selecting already-visible cells.

</details>

Observed on Ubuntu with pyqt5 and with pyside2. Confirmed by @sandhya-sago on a Mac (thanks!).

----

### Update

Title: **"The scroll-to-hint default behaviour of TabularEditor is uncommon and difficult to change (ambiguous attribute name)"**

Thanks to @aaronayres35's investigation (see discussion) the issue can be narrowed down to being about the `scroll_to_row_hint` trait, which:
- has a misleading name: is used for column scrolling as well as row scrolling
- has a default that feels unnatural

**Comment by aaronayres35** [comment]
Hi @nicolasap-dm, thank you for the very clear issue and for taking the time to give MWE example code!

There is a `scroll_to_row_hint` trait on `TabularEditor` that may be useful here.  It defaults to "center", but setting it to "visible" seems to give similar results to the example you give at the end of the issue description when I tested on your MWE.

The trait name is also a bit misleading as here this is really a scroll to a column not a row.  In fact the same trait appears to be used in both cases, see:
https://github.com/enthought/traitsui/blob/974bbdab83823230da7ec6e8fd730be038576f57/traitsui/qt4/tabular_editor.py#L517-L535
I also am not seeing mention of this in the documentation

**Comment by aaronayres35** [comment]
Also, perhaps "center" really should not be the default behavior here.  As you mention, it is pretty uncommon among tabular editors in the wild.  "visible" may make more sense, but this also might be a surprising ux change for apps which were used to having the "center" default

**Comment by nicolasap-dm** [comment]
Thanks @aaronayres35, this trait is definitely what I was looking for and setting it to "visible" solves my problem!

From the code snippet you report, it seems clear that the name of the trait is misleading here. I'll rename the issue in order to switch the focus to naming / documentation.
