### ISSUE TITLE
Should UITester.find_by_name raise for invisible widget

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1541]
Related to: https://github.com/enthought/traitsui/issues/1291

This is an issue for discussion, which may result in actions to change the behaviour, or actions to change the documentation, or both.

In an example
```
class Foo(HasTraits):
    text = Str()
    count = Int()
    view = View(Item("text", visible_when="count > 1"), Item("count"))
```

This will still return a wrapper for the TraitsUI editor for `text:
```
tester = UITester()
with tester.create_ui(Foo()) as ui:
    tester.find_by_name(ui, "text")  # won't fail
```
This not-failing behaviour can be understood because the TraitsUI editor is still defined even if the widget is invisible for some other reasons.

However, from another perspective, if one considers `UITester.find_by_name` as an indirect proxy of a human, then one would expect `find_by_name` to fail because the corresponding widget is invisible. Then one is tempted to use this as an indirect check for visibility, which would not work:
```

with tester.create_ui(Foo()) as ui:
    try:
       tester.find_by_name(ui, "text")
    except ValueError:
        self.fail("The UI is not visible in the GUI")   # this will never fail for uses of 'visible_when'
```

Note that #1291 proposes a more explicit check:
```
UITester.find_by_name(ui, "text").inspect(IsVisible())
```

If the behaviour of `find_by_name` is to be retained, then it might be good to at least mention the fact that visibility is not taken into account in `find_by_name` (likewise, for `find_by_id`).

**Comment by kitchoi** [comment]
Opinion:
I would personally find the direct correspondence between the definition of TraitsUI editor (as is defined in `View(Item(...), Group(...))` easier to understand than having to take into account visibility implicitly. The former is more static and declarative, whereas the latter is mutable and involves more moving parts (visibility can be affected by container widgets' visibility).

**Comment by kitchoi** [comment]
Perhaps the implicit VS explicit is a stronger argument for not changing the behaviour: Not necessarily everyone reading this `UITester().find_by_name(ui, "text")` will interpret it to check for visibility as well, whereas `assertTrue(UITester().find_by_name(ui, "text").inspect(IsVisible()))` is a more explicit assertion that conveys the meaning of a test.

**Comment by aaronayres35** [comment]
> Perhaps the implicit VS explicit is a stronger argument for not changing the behaviour: Not necessarily everyone reading this `UITester().find_by_name(ui, "text")` will interpret it to check for visibility as well, whereas `assertTrue(UITester().find_by_name(ui, "text").inspect(IsVisible()))` is a more explicit assertion that conveys the meaning of a test.

I agree with this, I think it makes more sense to leave the behavior as unchanged.  However, it should be clearly documented somewhere that `find_by_name` and `find_by_id` do not take visibility into account

**Comment by kitchoi** [comment]
Thank you @aaronayres35 

I opened https://github.com/enthought/traitsui/issues/1570 to track the documentation task.

I will close this now. However if anyone wants to advocate an alternative, please feel free to reopen this issue or open a new issue.
