### ISSUE TITLE
Add links to api docs on Predefined Editor Factories page in docs

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1591]
see: https://github.com/enthought/traitsui/pull/1560/files#r618940545 

currently, we manually list the "optional parameters" for each editor.  it would make sense and would be cleaner to link to the api docs directly.

**Comment by rahulporuri** [comment]
@aaronayres35  this looks to be a duplicate of #1561 . Is that right?

**Comment by aaronayres35** [comment]
> @aaronayres35 this looks to be a duplicate of #1561 . Is that right?

whoops, yep this can be closed
