### ISSUE TITLE
Consider renaming new scroll_to_position_hint trait 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1605]
see PR #1560 and specifically comment https://github.com/enthought/traitsui/pull/1560#pullrequestreview-644261644

**Comment by kitchoi** [comment]
The new `scroll_to_position_hint` has been released in TraitsUI 6.2. To avoid deprecation warnings from using `scroll_to_row_hint`, one would follow the instruction to use `scroll_to_position_hint`. It might be too late to rename the trait yet again.

**Comment by aaronayres35** [comment]
> The new `scroll_to_position_hint` has been released in TraitsUI 6.2. To avoid deprecation warnings from using `scroll_to_row_hint`, one would follow the instruction to use `scroll_to_position_hint`. It might be too late to rename the trait yet again.

You are right, I believe it is too late now.  For better or worse we are pretty much stuck with the current name, so I will close this issue.  Thanks @kitchoi !
