### ISSUE TITLE
RangeEditor does not support format_func

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#1650]
All editors have two traits to support converting values into strings for display:

- `format`, which is a `%`-style format string
- `format_func`, which is an arbitrary callable

However the `RangeEditor` completely ignores the existence of `format_func` and only ever uses `format`.  This is a problem if you wanted to display values as times or something similar (the particular use-case here is that we want to display frame numbers as `{minute}:{second}.{fractions of a second}` but we can't do that from an integer value with just `%` strings).

An alternative would be to provide a "slider-only" range editor which allows end-users to supply their own text field with whatever formatters they want.

**Comment by mdsmarte** [comment]
> An alternative would be to provide a "slider-only" range editor which allows end-users to supply their own text field with whatever formatters they want.

This might be useful in general. For example, if you want to change the width of the text box or other styling.

I was also going to say that this would be useful for parsing user input in `{minute}:{second}` format as int/float but it looks like the `evaluate` trait of `RangeEditor` would already make that possible.
