### ISSUE TITLE
Opening context menu from TableEditor with empty list

### ISSUE THREAD

**Issue by bebaek** [enthought/traitsui#1675]
If rows are deleted and the table is empty, a right-click anywhere on the table doesn't open the context menu. This necessitates an extra button or so to allow the user to add the first item. Otherwise, a context menu could have been sufficient to edit the table (add/delete). (In contrast, a context menu can be opened from ListStrEditor even when the list is empty.)

**Comment by corranwebster** [comment]
You should get a menu with "Add Item" in the empty area (I'm assuming you are on Qt):
https://github.com/enthought/traitsui/blob/0c30b77bc5cf6ba8aa4512f4e32834da269c83c4/traitsui/qt4/table_editor.py#L218-L221

Do you have the `editable` flag set, and have you provided a `row_factory` to create a new element with?
https://github.com/enthought/traitsui/blob/0c30b77bc5cf6ba8aa4512f4e32834da269c83c4/traitsui/qt4/table_editor.py#L1015-L1017

**Comment by bebaek** [comment]
Thanks! Exactly what I needed.
