### ISSUE TITLE
TableEditor.selection_color appears to work on Qt, but documentation says otherwise

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/traitsui#1700]
Both these traits on `TableEditor` are documented as ineffective on Qt:

https://github.com/enthought/traitsui/blob/42a42d5564a2f2beb7ff0bdab932673eba9fd78d/traitsui/editors/table_editor.py#L225-L229

but both seem to work on Linux with Qt5 and Pyside2, and at least `selection_color` works on windows too (I haven't tested `selection_bg_color`)

**Comment by aaronayres35** [comment]
Thank you for pointing this out!

I haven't tested anything locally to see that these work, but digging a little through github history I found the following:
There was an old issue about Qt TableEditor missing features (#594), some of which was addressed by #597
In the first commit of #597 (https://github.com/enthought/traitsui/pull/597/commits/7253ccb3c11c09d7fc8289e4e93fcc3e4fa646e7) those "Does not work on Qt." comments were added, however the second commit (https://github.com/enthought/traitsui/pull/597/commits/9b5591a146859666b6ff403a4e20ec157997a6b7)
seems to be using `factory.selection_bg_color` and `factory.selection_color`.  I suspect this did the trick of fixing this and the comments just didn't get removed (?)

After testing to verify this is the case, these comments can simply be removed
