### ISSUE TITLE
`TextEditor` evaluating functionality does not work on initial values

### ISSUE THREAD

**Issue by xamcost** [enthought/traitsui#1736]
Hi there! This small issue is to report a small bug, occurring when using a `TextEditor` with an `evaluate` function passed to it. As illustrated in the code snippet and movie below, we would expect that if the value of the string rendered by `TextEditor` is rejected by the `evaluate` function, the text field should appear red: that is true if the text is _modified_, but it does not happen if the _initial_ value of the string is rejected.

```Python3
from traits.api import HasStrictTraits, Str
from traitsui.api import TextEditor, UItem, View


class Foo(HasStrictTraits):

    name = Str("test")

    def validate_name(self, name):
        if name != "test":
            return name

    def default_traits_view(self):
        return View(
            UItem("name", editor=TextEditor(evaluate=self.validate_name))
        )


if __name__ == "__main__":
    foo = Foo()
    foo.configure_traits()
```

https://user-images.githubusercontent.com/24434420/126479144-97ce7fe7-49b4-44a6-b3d0-6d45bca70693.mov

**Comment by rahulporuri** [comment]
Closing as a wont-fix. This is similar to other known issues in traits/traitsui where we assume that you don't provide an object that's already in an invalid state.
