### ISSUE TITLE
Qt TreeEditor: Incorrect item added via context menu

### ISSUE THREAD

**Issue by pedrorivotti** [enthought/traitsui#1744]
Using the context menu to add an item in a `TreeNode` sometimes results in the wrong item being added (the last option in the list is always chosen). This is illustrated in the video below. 

https://user-images.githubusercontent.com/44579232/129049493-8afd5e2b-56b9-4270-8486-386d2ee54e4b.mov

From a quick investigation, the problem seems to be in this loop:
https://github.com/enthought/traitsui/blob/21aa39da97f4103b7f748845ca6f70888d9115a3/traitsui/qt4/tree_editor.py#L1093-L1095

A replacement along these lines could possibly fix it:

```python
            def perform_add(object, factory, prompt):
                self._menu_new_node(factory, prompt)
            items.append(Action(name=name, on_perform=partial(perform_add, factory=factory, prompt=prompt)))
```

<details><summary>MWE (tested with traitsui 7.2.1-1)</summary>

```python
from traits.api import HasTraits, Instance, List, Str
from traitsui.api import View, TreeEditor, TreeNode, UItem

class Folder(HasTraits):
    name = Str('Folder')
    children = List()

class SingleItem(HasTraits):
    name = Str('Item')

tree_editor = TreeEditor(
    nodes=[
        TreeNode(
            node_for=[Folder],
            children='children',
            label='name',
            add=[Folder, SingleItem],
            auto_open=True,
            view=View([]),
        ),
        TreeNode(
            node_for=[SingleItem],
            label='name',
            view=View(),
            auto_open=True,
        ),
    ]
)

class A(HasTraits):
    container = Instance(Folder, ())
    traits_view = View(
        UItem(name='container', editor=tree_editor),
    )

A().configure_traits()
```

</details>

**Comment by rahulporuri** [comment]
@pedrorivotti if you have a fix in mind, can you or someone on your team make the time to open a PR? The ETS team is short staffed at the moment and we might not be able to fix this soon
