### ISSUE TITLE
macOS Big Sur default accent color produces "blank" tabs

### ISSUE THREAD

**Issue by silverjam** [enthought/traitsui#1749]
When running our app on macOS Big Sur, we're seeing that the default "accent" color on macOS Big Sur causes active tabs to appear blank:

<img width="801" alt="Screen Shot 2021-09-07 at 2 12 14 PM(1)" src="https://user-images.githubusercontent.com/183436/132631120-140c6123-84ff-4ad1-ab90-ce8890d05077.png">

On macOS Mojave things appear correctly:

![Screenshot 2021-09-08 225014](https://user-images.githubusercontent.com/183436/132631163-3193ee2c-8d0a-4b9f-babc-dfac9ef193f8.png)

Is there a way to workaround this issue by adjusting a theme setting within the app?

**Comment by corranwebster** [comment]
I haven't migrated to Big Sur yet, so I haven't seen this but it hasn't been reported by any of my coworkers who have upgraded.  This looks like Qt, and there all of the tab coloring is done by Qt - TraitsUI generally gets out of the way of that stuff on Qt and lets it do its best (which sometimes isn't good enough, unfortunately).

Things to try (assuming Qt):
- if you haven't already, try setting the environment variable `QT_MAC_WANTS_LAYER=1` which reportedly improved Qt's behaviour on Big Sur
- updating the version of Qt that you are using (we don't have Qt6 support yet, unfortunately, but if you aren't on a recent version of 5.x this could be the cause).  It could also be worth seeing if there is different behaviour on PyQt5 vs PySide2, although I wouldn't expect it.
- compiling Qt with a more recent version of XCode (I don't know where you are getting your build of Qt, but I have read that if you build with more recent XCode it should properly support dark mode, for example).

If these don't work (or you aren't in the business of building your own versions of Qt), TraitsUI _does_ give hooks into the styling system of Qt.  There is a `style_sheet` argument that you can give to a `Group`, `Item` etc. that contains a Qt stylesheet as a string and it will be applied to all the Qt objects in that traitsui object.  I'm not sure what the right stylesheet info is for an active tab's colour, but it is surely somewhere in the [Qt Stylesheet Reference](https://doc.qt.io/qt-5/stylesheet-reference.html) - the class you want is probably `QTabBar` or `QTabWidget`.

And if you're on Wx, please ignore all of that and let me know - but some of the suggestions about versions of Qt will also apply to versions of Wx and WxPython.  But TraitsUI does more of its own styling on Wx and so it is more likely that this is a bug in TraitsUI.

**Comment by silverjam** [comment]
Thanks for the suggestions, and yes we're using Qt, we'll give these suggestions a try.

I have tried updating PyQt in the past but have not had success, finding a version combination of Python + PyQt/PySide + PyInstaller that all works together well has been a challenge.

**Comment by silverjam** [comment]
Updating to PySide2 5.15.2 worked to resolve the problem, I tried PyQt5 version 5.15.4 but this crashed (segmentation fault) on startup.
