### ISSUE TITLE
Getting TraitsUI edit_traits() to display in Jupyter notebook

### ISSUE THREAD

**Issue by glinsky007** [enthought/traitsui#1794]
There my be a very simple fix for this, but when I try to execute the edit_traits method from a Jupyter notebook nothing happens.  It is identical to the behavior when this is done from iPython without the --pylab option.

**Comment by corranwebster** [comment]
You need a Qt or Wx event loop to be running for `edit_traits` to work.  Try doing `%gui qt` in a cell (or similar, see https://ipython.readthedocs.io/en/stable/config/eventloops.html) and then doing `edit_traits`.  Possibly doing `configure_traits` will also work, but it may block IPython execution and cause problems.

**Comment by glinsky007** [comment]
This works!

**Comment by glinsky007** [comment]
Attached is a Jupyter notebook that demonstrates that this solution works.  Note that the TraitsUI GUI appears behind the browser window.
[traits_error_demo.ipynb.zip](https://github.com/enthought/traitsui/files/7946520/traits_error_demo.ipynb.zip)

**Comment by corranwebster** [comment]
Closing this - I think it is resolved.
