### ISSUE TITLE
Docs and source licenses are different

### ISSUE THREAD

**Issue by achabotl** [enthought/traitsui#1814]
I spotted that the license in the [TraitsUI docs](https://docs.enthought.com/traitsui/traitsui_user_manual/index.html#license) and in [the source](https://github.com/enthought/traitsui/blob/main/LICENSE.txt) are different. The former seems to be BSD-2-clause and the latter BSD-3-clause.

Not sure if it matters.

**Comment by corranwebster** [comment]
Probably doesn't matter, but also for consistency it makes sense to change the docs to 3 clause.

**Comment by corranwebster** [comment]
Looked into this - the TraitsUI docs isn't [2 clause BSD](https://opensource.org/licenses/BSD-2-Clause) but rather a variant of the 3-clause BSD which removes mention of binary format and adds information about derived document formats to the first clause.  It keeps the non-endorsement clause.

So I think I'm OK with leaving this as-is
