### ISSUE TITLE
Multiple toolkit warnings

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#1837]
From the Mayavi team: reporting seeing warning messages like the following:
```
multiple 'pyface.toolkits' plugins found for toolkit 'qt4': pyface.ui.qt4.init, pyface.ui.qt4.init
multiple 'traitsui.toolkits' plugins found for toolkit 'qt4': traitsui.qt4, traitsui.qt4
```

**Comment by prabhuramachandran** [comment]
This is certainly PEBKAC, I somehow had 5 different traitsui installs.  So if someone is looking to fix this issue on their setup, the solution is to have a single installation of pyface or traitsui in your site-packages.
