### ISSUE TITLE
RangeTextEditor errors out when low or high limit in Range trait is not set

### ISSUE THREAD

**Issue by oeyh** [enthought/traitsui#1923]
RangeTextEditor checks if value is between low and high limit (PR #1731) but it doesn't consider the case where either low or high is not set (equals to `None`) in the corresponding `Range` trait, which is used to indicate no limit on that end. This change breaks some existing project code.

Wondering if this is an intended change to enforce both low and high limit to be set explicitly. 

A minimum reproducible example:
```python
from traits.api import HasTraits, Range
from traitsui.api import Item, View


class Experiment(HasTraits):
    # sigma = Range(low=0, high=5, value=3)  # works
    sigma = Range(low=0, value=3)  # no longer works
    # sigma = Range(high=5, value=3)  # no longer works

    def default_traits_view(self):
        return View(
            Item('sigma', style='text')
        )


if __name__ == '__main__':
    Experiment().configure_traits()

```

**Comment by JaRoSchm** [comment]
After updating several enthought packages I have the same problem.

**Comment by ctangell** [comment]
Getting this fixed soon would be dandy as this is blocking project migration to 3.8.
