### ISSUE TITLE
_default() methods only call functions, instancemethods

### ISSUE THREAD

**Issue by rdgraham** [enthought/traitsui#193]
I have noticed that if a define a _name_default() for a given trait in a traitsUI class, it only seems to be called if it is a method defined inline with `def` or a lambda. I may be misunderstanding something but it seems to me that any callable object should work.

For example I have a class SettingsLoader which defines a `__call__` method and deals with loading default values in some cases. Wrapping it in a lambda expression works but I don't know why that is necessary. eg:
```python
    class A(HasTraits):
        foo = String('')
        _foo_default = lambda self : SettingsLoader('foo')()
```

**Comment by mdickinson** [comment]
Thanks for the report, @rdgraham.  It looks as though this report is specific to the Traits core library rather than the Traits UI system, so I've re-reported it at enthought/traits#230.  I'll close this report and follow up there.
