### ISSUE TITLE
progress_column skips a row

### ISSUE THREAD

**Issue by sallenEnth** [enthought/traitsui#1936]
I tested the demo for the table_editor_with_progress_column but there is an issue with a row skipped so the progress bar is not on the right row, except for the first one. I tested on Linux and Windows and got the same results. This was for:

- Python 3.6
- traitsui 7.4.0
- pyface 7.4.2

I also tried to fix a large `row_height` to the `table editor` and set `auto_size = False`, but it just increases the size of the row and there is still a row skipped.
![progress_column](https://user-images.githubusercontent.com/12350485/190339428-f3caed41-f7d8-40f5-9b31-650b070a8b42.png)

**Comment by corranwebster** [comment]
Which Qt backend is this?

**Comment by aaronayres35** [comment]
These are probably relevant https://github.com/enthought/traitsui/issues/964 / https://github.com/enthought/traitsui/pull/1721

**Comment by sallenEnth** [comment]
Thank you for the suggestion @aaronayres35. When I undo the change made in PR #1721 everything works fine.
@corranwebster I am using pyside2 5.14.2.3 with qt 5.12.6. Since we are planning to move to Python 3.8, I also tested it with pyside6 v 6.2.3 and qt 6.2.3 and I get the exact same behavior.

Note that the test for python 3.6 were run in the similar environment on a Linux platform, a Windows VM, and a Windows platform and it gives always the same result.

**Comment by corranwebster** [comment]
The fix for #1721 was for a bug on the mac, so it is possible that we need to add a check for whether `sys.platform` is "darwin" and only then do the translation?

**Comment by corranwebster** [comment]
@sallenEnth Can you please review #1937 and make sure it resolves your issue.
