### ISSUE TITLE
Table Editor Right Click Exception

### ISSUE THREAD

**Issue by JackDra** [enthought/traitsui#1947]
### Summary

Present on:
- python v3.6
- `traitsui==7.4.0-2`
- `pyside2==5.14.2.3-2`
- Windows `win_x86_64`

Same issue happens on python 3.8 with traitsui and pyside6

If 3 conditions are present on a traitsui view:
- `scrollable` set to `True`
- Anything in the view that has `visible_when` kwarg
- Table editor that is right clickable (reorderable etc..)

Then when that `visible_when` clause is `True` , it causes the table editor to not be right clickable, and the error message shows:
```python
Traceback (most recent call last):
  File "C:\Users\jdragos\.edm\envs\tires\lib\site-packages\traitsui\qt4\table_editor.py", line 1046, in eventFilter
    editor.header_menu_up.setVisible(show_up)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QAction) already deleted.
```

### Example
Right clicking the table initially is fine, but after clicking the button and making the text invisible, right clicking the table causes an error.
The same error occurs if you initially set `show_text_toggle` to `False` to initially have the text invisible too

```python
from traits.api import Bool, Button, HasTraits, Instance, Int, List, Str
from traitsui.api import Item, ObjectColumn, TableEditor, UItem, View


class Row(HasTraits):

    col1 = Int()
    col2 = Str()


class RightClickTable(HasTraits):

    rows = List(Instance(Row))

    invis_text = Str("Invisible!")

    show_text = Button()

    show_text_toggle = Bool(True)

    def _show_text_changed(self):
        self.show_text_toggle = not self.show_text_toggle

    view = View(
        UItem(
            "rows",
            style="custom",
            editor=TableEditor(
                columns=[
                    ObjectColumn(name="col1"),
                    ObjectColumn(name="col2")
                ],
                rows=True,
                reorderable=True,
            ),
        ),
        UItem("show_text"),
        Item("invis_text", style="readonly", visible_when="show_text_toggle"),
        scrollable=True
    )


if __name__ == "__main__":
    rows = [
        Row(col1=1, col2="hi"),
        Row(col1=2, col2="bye"),
    ]
    table_ui = RightClickTable(rows=rows)
    table_ui.configure_traits()
```

**Comment by corranwebster** [comment]
I can reproduce on macOS/PySide6, so this is looks like a fairly widespread bug.

A very quick look at the code for the context menus, the menu is being created when the editor widget is created and the persisted through the lifetime of the editor; and then the menu is modified at the point of display. But something seems to be collecting the C++-side objects so the attempt to modify the menu is failing.

A better approach may be to create the menu objects dynamically at the point of need - this is the approach taken by the tree editor, for example.

Fixing this is a moderately large change to the editor.
