### ISSUE TITLE
string_list_editor_example.py fails in wx

### ISSUE THREAD

**Issue by jdmarch** [enthought/traitsui#26]
Seems to run ok in qt.

in wx, fails at wx/ui_panel.py, line 1045, reference to undefined editor.border_size.

This is apparently because the example's class StringListEditor is not defined to be toolkit-independent, so that editor is just a UIEditor rather than an instance of the wx-specific subclass.

**Comment by corranwebster** [comment]
This seems to be running fine now (at least on OS X).  Closing.
