### ISSUE TITLE
`_version.py` file is missing from `traitsui/`

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#272]
I tried building the docs using Sphinx but it failed because `conf.py` in `docs/source` wants to run the file.

**Comment by mdickinson** [comment]
Yes, you need to have done a `python setup.py develop` first. The `_version.py` file is autogenerated.

**Comment by dpinte** [comment]
@mdickinson `pip install -e .` !!!!!

**Comment by mdickinson** [comment]
@rahulporuri: Don't close *too* quickly! I think there's still an issue here - the fact that it wasn't obvious how to build the docs is itself a doc bug. Perhaps there should be a `README` file in the docs directory with that information in?

**Comment by rahulporuri** [comment]
ohh. sorry.

well, there was one other problem I encountered while building the docs. running `make html` gave the following warning 
`<string>:157: RuntimeWarning: Can't find Enthought Sphinx Theme, using default.
Exception was: No module named enthought_sphinx_theme `
I looked around and found a repository by the same name in enthought/ and making docs with the theme installed changed the outlook completely from the current one (ofcourse!)

currently, the docs use a .css file and a logo file on top of the `default` sphinx theme.

1. Use the enthought_sphinx_theme, which will make the traits docs have the same look as the pyface docs do
2. Remove any reference to enthought_sphinx_theme and go ahead with the `default` theme.

**Comment by mdickinson** [comment]
Right; the information how to get and use the Enthought sphinx theme would be another candidate for the doc-building docs!

**Comment by corranwebster** [comment]
Regarding how to handle doc themes, do number 1: you should install the Enthought Sphinx theme.

When I switched the docs over to use the new theme I didn't want to break docs for anyone in the community, I didn't want to add a dependency that wasn't needed for runtime support, but I also wanted to give a clue as to why someone might not get the Enthought Theme if they were expecting it.

We still need to switch the style of a lot of the other projects.

**Comment by rahulporuri** [comment]
@corranwebster  if that is the case, shouldn't we also point them to the theme, so that they can install it if they want to?

**Comment by corranwebster** [comment]
Pull requests will be gladly accepted (relevant code is probably in `conf.py`) :)

**Comment by rahulporuri** [comment]
i've submitted a PR #273
