### ISSUE TITLE
Qt TreeEditor dragging: mouse pointer offset from item being dragged.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#292]
When dragging an item from a `TreeEditor` with Qt backend, the pointer can end up offset by some distance from the text bar indicating the item being dragged. The effect is particularly pronounced when it takes time to compute the drag object.

Code demonstrating the issue:

```python
import time
from traits.api import HasTraits, Instance
from traitsui.api import TreeEditor, TreeNode, UItem, View

class MyTree(HasTraits):
    pass

class MyTreeNode(TreeNode):
    def get_drag_object(self, object):
        time.sleep(0.5)
        return object

class TreeView(HasTraits):
    tree_model = Instance(MyTree)

    def default_traits_view(self):
        return View(
            UItem(
                'tree_model',
                editor=TreeEditor(
                    nodes=[
                        MyTreeNode(
                            node_for=[HasTraits],
                            children='',
                            label='=Drag me',
                        ),
                    ]
                )
            ),
            resizable=True,
        )


if __name__ == '__main__':
    model = MyTree()
    view = TreeView(tree_model=model)
    view.configure_traits()
```

**Comment by corranwebster** [comment]
If I had to guess, this is probably the line which is responsible for the problem: https://github.com/enthought/traitsui/blob/master/traitsui/qt4/tree_editor.py#L1781

**Comment by mdickinson** [comment]
Agreed. It looks as though to do this correctly we need access to the mouse-down position that preceded the drag event. I can't see an easy way to get that without overriding `mousePressEvent` in our `QTreeWidget` subclass.

**Comment by pankajp** [comment]
An easier way to reduce the offset might be to get the cursor position at the beginning of the method itself, before getting the drag object and doing all the computations.

**Comment by corranwebster** [comment]
Actually, just moving that line further up the method (in particular, before trying to get the node data) seems to work.

**Comment by mdickinson** [comment]
Yes, that should improve things a bit. It's not really a fix, though, since it's using the current mouse position at the point where the drag started (which is distinct from the mouse-down position that preceded the drag).
