### ISSUE TITLE
Using traits and traitsui QString issue

### ISSUE THREAD

**Issue by UID1** [enthought/traitsui#294]
When using traits and traitsui on python with "ipython -pyplot" on Linux or "ipython --matplotlib" on Windows I get the error message:

"ValueError: API 'QString' has already been set to version 1" in 
"~/anaconda2/lib/python2.7/site-packages/guidata/qt/**init**.py"

I got this error by first running say

``` python
import numpy as np
import traits.api as trapi

class short_rate(trapi.HasTraits):
  name = trapi.Str
  rate = trapi.Float
  time_list = trapi.Array(dtype=np.float, shape=(5,))
  def get_discount_factors(self):
    return np.exp(-self.rate * self.time_list)

sr = short_rate()
sr.configure_traits()
```

---

First it complained that traitsui wasn't found. So I installed with `conda install traitsui`. Then I repeated the last command and got this error as mentioned above.

How can I deal with this?

**Comment by mdickinson** [comment]
https://github.com/pierreraybaut/guidata/issues/35 looks related.

**Comment by corranwebster** [comment]
Are you on Python 2.7 or python 3.x?  And I assume that you are using Qt4 rather than Qt5.

A short term work-around may be to install and use PySide instead of PyQt4: use the environment variable `QT_API="pyside"` to select between it and PyQt.
