### ISSUE TITLE
items tutorial causes bus error

### ISSUE THREAD

**Issue by cfarrow** [enthought/traitsui#3]
The tutorial entitled Extended Traits UI Item and Editor References causes a bus error when run from the tutor application.
This is running all of ETS from the master on OSX 10.6.

Start tutor.py under traitsui/examples/tutorials and click on the mentioned tutorial.

**Comment by rahulporuri** [comment]
Closing as I can't reproduce this at the moment. FTR, the example is https://github.com/enthought/traitsui/blob/master/examples/tutorials/traitsui_4.0/items.py
