### ISSUE TITLE
Date picker does not work if you import wx.combo first

### ISSUE THREAD

**Issue by will133** [enthought/traitsui#303]
It seems like there are Date picker is somewhat broken with wx and traitsui.  I try the following script (a stripped down example from the date editor).

```python
import wx._combo
from traits.api import HasTraits, Date
from traitsui.api import View, Item


class DateEditorDemo(HasTraits):
    date = Date
    view = View(Item('date'), resizable=True)


if __name__ == "__main__":
    demo = DateEditorDemo()
    demo.configure_traits()
```

I get this following stack:

```
Traceback (most recent call last):
  File "t.py", line 15, in <module>
    demo.configure_traits()
  File ".../lib/python2.7/site-packages/traits/has_traits.py", line 2156, in configure_traits
    kind, handler, id, scrollable, args )
  File ".../lib/python2.7/site-packages/traitsui/wx/toolkit.py", line 219, in view_application
    id, scrollable, args )
  File ".../lib/python2.7/site-packages/traitsui/wx/view_application.py", line 93, in view_application
    scrollable, args ).ui.result
  File ".../lib/python2.7/site-packages/traitsui/wx/view_application.py", line 141, in __init__
    super( ViewApplication, self ).__init__(0)
  File ".../lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 8631, in __init__
    self._BootstrapApp()
  File ".../lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File ".../lib/python2.7/site-packages/traitsui/wx/view_application.py", line 158, in OnInit
    args       = self.args )
  File ".../lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File ".../lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File ".../lib/python2.7/site-packages/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 349, in panel
    content[0], ui )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 523, in fill_panel_for_group
    create_panel )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 672, in __init__
    self.add_items(content, panel, self.sizer)
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 1087, in add_items
    self._set_owner( control, item )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 1236, in _set_owner
    self._set_owner( child, owner )
  File ".../lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 1234, in _set_owner
    control._owner = owner
AttributeError: 'PySwigObject' object has no attribute '_owner'
./src/common/module.cpp(194): assert "module->m_state == State_Initialized" failed in DoCleanUpModules(): not initialized module being cleaned up
```

From the debugger, it looks like the control variable is a pySwigObect which does not allow you to set the attribute _owner.

The strange thing is that if you do not import that wx._combo line, it would work.  The wx._combo is being import from wx.combo (which is where I discovered the problem).

I'm running this through the following conda environment (from conda list):

```
mkl                       11.3.3                        0
numpy                     1.11.1                   py27_0
openssl                   1.0.2h                        1
pip                       8.1.2                    py27_0
pyface                    4.5.2                    py27_0
pygments                  2.1.3                    py27_0
python                    2.7.12                        1
readline                  6.2                           2
setuptools                26.1.1                   py27_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
traits                    4.5.0                    py27_0
traitsui                  4.5.1                    py27_0
wheel                     0.29.0                   py27_0
wxpython                  3.0.0.0                  py27_2
zlib                      1.2.8                         3
```

**Comment by corranwebster** [comment]
Thanks for the report.  Unfortunately, I don't see the error when running on my system (current master branch of TraitsUI and Pyface, WxPython 3.0.2, OS X).

The most likely cause is that PyFace and TraitsUI 4.5.x don't properly support WxPython 3 (some things work, some things cause weird errors like what you are seeing).  Please try either:

- downgrading to WxPython 2, or
- updating Pyface and TraitsUI to 5.1 which should support WxPython 3.

Note that the default toolkit used by TraitsUI has changed to Qt in 5.1, but as long as you don't have either PySide or PyQt installed, you should be fine.

I'm going to close the issue, since we don't expect TraitsUI 4.5 to work with WxPython 3, but please re-open if it persists with TraitsUI 5.1 or later.

**Comment by will133** [comment]
I've tried this on the latest TraitsUI (from github master) with the latest wxpython 3.0.2.0 and I still see this issue, so I think this should be reopened.  I'm running this in a Linux host.  It seems like the _owner attribute can not be set on a raw swig object.

**Comment by corranwebster** [comment]
Fair enough.  Thanks once again for the report.

@RobinD42 Do you have any particular insight into this issue?

**Comment by will133** [comment]
I debugged a little more about this.  When I try to put a debugger through around traitsui/wx/date_editor.py:58:

```python
        self.control = date_widget(parent,
                                   size=(120, -1),
                                   style=wx.DP_DROPDOWN
                                   | wx.DP_SHOWCENTURY
                                   | wx.DP_ALLOWNONE)
```

Note that date_picker in box cases are wx.DatePickerCtrl.

Without the wx._combo import, calling self.control.GetChildren() would yield:

```python
wxWindowList: [<wx._core.Control; proxy of <Swig Object of type 'wxControl *' at 0x23d81e0> >]
```

With the wx._combo import (where I get an exception with the _owner attribute not found), the self.control.GetChildren() would get:

```python
wxWindowList: [<Swig Object of type 'wxComboCtrl *' at 0x32244c0>]
```

I don't know swig that well so I'm not sure why it would return different content when wx._combo is imported or not.  It seems like there's something weird going on where the swig wrapper would not be initialized correctly?

**Comment by will133** [comment]
I've filed http://trac.wxwidgets.org/ticket/17649 as well.  In that issue I have a pure wx version without traits that would trigger this condition as well.  However, from the wxpython perspective it seems like the GUI would show up correctly even with this condition triggered.  I'm not sure what setting the _owner attribute would accomplish though in traitsui, so I'm not completely sure that this is purely a wxpython bug.  Unfortunately this is a showstopper for us so I'm trying to figure out how to work around this.

**Comment by RobinD42** [comment]
Thanks for all the details.  The note about GetChildren differences is a good clue which points to an issue related to how the correct class is being located for wrapping a new proxy around an existing C++ pointer.  I'll take a closer look at that when I have some time.

**Comment by will133** [comment]
Thanks @RobinD42 for the response.   After some gdb debugging, it looks like when wx._combo is imported, the proper SWIG converter is being registered such that the proper class wxComboCtrl is known.  Therefore, instead of the wx._core.Control top level that gets returned, the more sepcific wxComboCtrl's wrapper is there.  Unfortunately the wrapper for the wx._core.Control and wxComboCtrl are somewhat different (I'd imagine the wxComboCtrl would be a subclass of that).  This is probably a bug on the wx side but I guess that returning the wrapped wxComboCtrl is probably the right behavior.

The question is then how traitui can handle this case.  Does anybody have any insight on the code around traitsui/wx/ui_panel.py:1234 where the _set_owner function is doing this?

```
    control._owner = owner
```

I'm having a hard time trying to follow where the  _owner attribute is used.
