### ISSUE TITLE
qt4/enum_editory.py Python 3 bug

### ISSUE THREAD

**Issue by ericjmcd** [enthought/traitsui#309]
I reported this bug already here but it got closed.
#306 
I added a comment there but I guess that wasn't enough to reopen it.

Anyway,
`incr = [ n / cols ] * cols (line 432)`
is the line that is still incorrect (it creates a list of floats since `n/cols` returns a float in Py3). That incr list is eventually referenced for index values which throws the exception.
[https://github.com/enthought/traitsui/blob/master/traitsui/qt4/enum_editor.py#L432](url)

**Comment by corranwebster** [comment]
Right, I see. Closing in favour of the original (#306) which I have re-opened.
