### ISSUE TITLE
ListEditor's left side button cannot be clicked

### ISSUE THREAD

**Issue by BotChen** [enthought/traitsui#312]
Program: traitsui/examples/demo/Standard_Editors/ListEditor_demo.py
Problem: no menu shown when clicking the blue button of ListEditor
System:
Python 3.5
latest traitsui from pypi
PyQt4 downloaded from http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by corranwebster** [comment]
This is fixed by #330
