### ISSUE TITLE
Lines missing in \traitsui\qt4\tree_editor.py (Windows)

### ISSUE THREAD

**Issue by yves-surrel** [enthought/traitsui#317]
After experiencing problems of different behaviors between the MacOSX platform and the Windows platform with TreeNodes without any 'view' field, I found that in the Windows installation (1.7.4.3348 (64 bit)), the following lines near the end **_on_tree_sel_changed** of tree_editor.py were:

                # Finish setting up the editor:
                ui.control.layout().setContentsMargins(0, 0, 0, 0)

instead of:

                # Finish setting up the editor:
                if hasattr(ui.control.layout(), 'setContentsMargins'):
                    ui.control.layout().setContentsMargins(0, 0, 0, 0)

as in the MacOSX installation

**Comment by corranwebster** [comment]
@yves-surrel The second set of code with the if statement isn't in the TraitsUI codebase master branch.  What was the source of your installation for OS X?

**Comment by yves-surrel** [comment]
Not sure I understand your question. I regularly downloaded 1.7.4.3348 
(64 bit) for MacOSX from the Enthought website.

Yves

Le 2016-11-23 15:47, Corran Webster a écrit :

**Comment by jdmarch** [comment]
@yves-surrel I think this is not a traitsui issue but a Canopy configuration / reset  issue. Please email support@enthought.com.

**Comment by corranwebster** [comment]
Hopefully this resolved.  Closing for now.
