### ISSUE TITLE
Error running TreeEditor_demo.py

### ISSUE THREAD

**Issue by michaelcoon** [enthought/traitsui#323]
Using python 3.4, traitsui 5.1.0 and qt4, I get an error running 
https://github.com/enthought/traitsui/blob/master/examples/demo/Standard_Editors/TreeEditor_demo.py

The error occurs when I try to edit the Name property of an Employee node.  Editing other fields (Title, Phone) works properly.  The error below occurs as soon as any change is made in the Name text box.

	Exception occurred in traits notification handler.
	Please check the log file for details.
	Exception occurred in traits notification handler for object: <__main__.Employee object at 0x0000000007AECF10>, trait: name, old value: Dave, new value: Davew
	Traceback (most recent call last):
	  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda2\envs\proj\lib\site-packages\traits\trait_notifiers.py", line 519, in _dispatch_change_event
		self.dispatch( handler, *args )
	  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda2\envs\proj\lib\site-packages\traits\trait_notifiers.py", line 614, in dispatch
		handler( *args )
	  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda2\envs\proj\lib\site-packages\traitsui\qt4\tree_editor.py", line 1606, in _label_updated
		if nid not in nids:
	TypeError: unhashable type: 'QTreeWidgetItem'

Is this a problem with my environment?  Any suggestion would be appreciated as I would like to use similar functionality in another application.

**Comment by jdmarch** [comment]
Reproduced with EDM Python 3.5.2, PyQt-4.11.4-7, traitsui 5.1.0-2 
Not reproduced with EDM Python 2.7.12, same pkg versions, nor with Canopy Python 2.7.11

**Comment by corranwebster** [comment]
Probably related: https://github.com/enthought/pyface/issues/235

**Comment by jdmarch** [comment]
@corranwebster issue (or related) still appears to be present in Python 3.6.
See http://stackoverflow.com/questions/43157914/treeeditor-demo-py-raises-typeerror-in-python-3

Reproduced with EDM Python 3.6.0, traitsui 5.1.0, pyqt 4.11.4
Reopening.
