### ISSUE TITLE
traitsui/view.py:View.ui incompatible with has_traits

### ISSUE THREAD

**Issue by spichardo** [enthought/traitsui#324]
Hi,

In their current versions of [traitsui](https://github.com/enthought/traitsui/commit/c8ae6702c7074ee84b9df064e62b7a409f0155f8) and [traits](https://github.com/enthought/traits/commit/6613b0fb4fe465d4f78d1abe067ec92a22c2f8f9), the `View.ui` function is calling the old-fashion function to set properties of `has_traits`:
```python
    def ui(self, context, parent=None, kind=None,
            view_elements=None, handler=None,
            id='', scrollable=None,
            args=None):
...
        if args is not None:
            handler.set(**args)
...
```

`has_traits` complains that this method is now deprecated:

> ... Uncaught exception
> Traceback (most recent call last):
>   File "C:\Anaconda2\envs\py33\lib\runpy.py", line 160, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Anaconda2\envs\py33\lib\runpy.py", line 73, in _run_code
>     exec(code, run_globals)
>   File "E:\Github\HyperthermiaHeadAndNeck\MAIN_APP.py", line 1072, in <module>
>     main()
>   File "E:\Github\HyperthermiaHeadAndNeck\MAIN_APP.py", line 1068, in main
>     ex = HyperthermiaNeckApp(InitDir=InitDir,InitFile=InitFile)
>   File "E:\Github\HyperthermiaHeadAndNeck\MAIN_APP.py", line 187, in __init__
>     self.__initUI()
>   File "E:\Github\HyperthermiaHeadAndNeck\MAIN_APP.py", line 257, in __initUI
>     self.MainContainer=WidgetSlices(parent=self,DataDirectory=self.DataDirectory)
>   File ".\WidgetSlices.py", line 45, in __init__
>     self.slice_wdt[SelKey]=self.slice[SelKey].edit_traits(parent=self).control
>   File "E:\Github\Proteus\GUI\MRIInspection.py", line 121, in edit_traits
>     retVal = super(ShowSlice,self).edit_traits(parent=parent)
>   File "C:\Anaconda2\envs\py33\lib\site-packages\traits-4.7.0.dev2-py3.3-win-amd64.egg\traits\has_traits.py", line 1871, in edit_traits
>     handler, id, scrollable, args )
>   File "C:\Anaconda2\envs\py33\lib\site-packages\traitsui-5.2.0.dev55-py3.3.egg\traitsui\view.py", line 423, in ui
>     handler.set(**args)
>   File "C:\Anaconda2\envs\py33\lib\site-packages\traits-4.7.0.dev2-py3.3-win-amd64.egg\traits\util\deprecated.py", line 31, in wrapper
>     warnings.warn(message, DeprecationWarning, stacklevel=2)
> DeprecationWarning: use "HasTraits.trait_set" instead

For the moment to make it work I'm disabling in `has_traits` the `@deprecate` decorator:
```python
    # Defines the deprecated alias for 'trait_set'
    #@deprecated('use "HasTraits.trait_set" instead')
    def set ( self, trait_change_notify = True, **traits ):
        return self.trait_set(
            trait_change_notify=trait_change_notify, **traits)
```

Any ideas how in the `ui` function the properties should be set now using the new`has_traits` convention?

**Comment by corranwebster** [comment]
The fix is to replace all uses of `set` with `trait_set` in TraitsUI and all other upstream packages.

However, this is a deprecation warning - functionality is not affected - so the simplest workaround is to turn off deprecation warnings using the warnings module.

**Comment by spichardo** [comment]
yes, I should rather suggest changing using `trait_se` in traitsui/view.py:`View.ui` function:
```python
    def ui(self, context, parent=None, kind=None,
            ...
        if args is not None:
            handler.trait_set(**args)
```

It also works like with of course.

On a side note, I was not able to disable the exception triggered by the @deprecated decorator using : 
```
import warnings
warnings.filterwarnings('ignore')
```
And not only for this specific deprecated warning, for any other similar warning I could not find how exactly to disable them, I also tried setting ` PYTHONWARNINGS="ignore"`. I remember longtime ago this always worked, but for this Pyside-based applications it seems the ignore level is ignored. Anyway that is a totally separate problem.

**Comment by corranwebster** [comment]
```
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
```
ought to work for turning the warnings off, but it needs to happen very early in your code (ideally before your first import in your main module).

One question: are you seeing these during test runs, or when running the app properly?  The traits unittest tools turn on all deprecation warnings, so that could be a possible cause of this.

In terms of looking at a proper fix, I actually looked into his last week, and it happens in enough places that fixing is non-trivial, and I don't think quite automatable.  It just needs someone to sit down and churn through a search for all occurrences and determine whether the change needs to be made or not (it's even worse with `get()`/`trait_get()`).

**Comment by spichardo** [comment]
These are appearing during running the application run, and yes, I was putting all the way to top of the main python Pyside application file the disabling of the warning...

Yeap.. this is way more than a single location ... super strangely, when I only did the change in view.py , under python3.3 all worked out. But now I started to do some tests in another anaconda environment with python2.7 and there you can see the old `.set ` is all over the place in traitsui and in chaco...

**Comment by corranwebster** [comment]
Closing this in favour of #333 which states the core problem more clearly.
