### ISSUE TITLE
Readonly vs. non-readonly specification lead to a different format

### ISSUE THREAD

**Issue by stefanoborini** [enthought/traitsui#344]
The following

```
    traits_view = View(
            VGroup(
                Item(
                    "model.name",
                    resizable=True,
                    style="readonly"
                ),
                Item(
                    "model.definition",
                    resizable=True,
                    style="readonly"
                ),
                Item("model.type",
                     style="readonly"
                     ),
                Item("model.shape",
                     editor=CSVListEditor(),
                     style="readonly"
                     ),
                Item(
                    "model.length",
                    visible_when="model.type == 'string'",
                    style="readonly"
                ),

                label="CUBA Data Type",
                show_border=True,
            ))
```

Results in this 
<img width="356" alt="untitled" src="https://cloud.githubusercontent.com/assets/132967/22832234/2c1a280a-efa5-11e6-8dc0-3007f3525d62.png">

However, if I remove the readonly, the result is more compact

<img width="356" alt="untitled2" src="https://cloud.githubusercontent.com/assets/132967/22832242/370aa7f8-efa5-11e6-955c-980d4a86178a.png">

**Comment by corranwebster** [comment]
DIfferent widgets under the covers (eg. QTextField vs. QLabels) so Qt has different default rules about how they can expand.  Try playing with `resizable=False` or perhaps if it fits the UX, just use the non-readonly version, but have `enabled_when='False'`

**Comment by stefanoborini** [comment]
True, but I think that if there's an underlying difference in the vertical expand, traitsui should guarantee that they behave the same.

**Comment by corranwebster** [comment]
Note that you will get different layout behaviour also if you make the textbox `style='custom'`, which I think will be closer to the readonly style.  Based on that, its not clear what's "correct" and what behaviour should be guaranteed.

TraitsUI is not designed for pixel-perfect layout.
