### ISSUE TITLE
ButtonEditor's custom style doesn't handle text updates.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#355]
To reproduce, run the following script:
```
from traits.api import HasTraits, Button
from traitsui.api import ButtonEditor, View, UItem

class A(HasTraits):
    play_button = Button("Play")

    traits_view = View(
        UItem(
            'play_button',
            editor=ButtonEditor(),
        ),
        style='custom',
    )

if __name__ == '__main__':
    a = A()
    a.configure_traits()
```

On my system (OS X 10.9.5, EDM 1.6.0, Python 2.7.13, traitsui 5.1.0-2, PySide 1.2.2-14), I see a blank button:

<img width="189" alt="screen shot 2017-05-18 at 17 07 11" src="https://cloud.githubusercontent.com/assets/662003/26212126/7b065a72-3bec-11e7-8de4-e80d3c40ef8b.png">

Looking at the [source](https://github.com/enthought/traitsui/blob/5.1.0/traitsui/qt4/button_editor.py#L123), it seems that the `CustomEditor` overrides the `init` method of the `SimpleEditor`, but doesn't sync-up label changes.

**Comment by rkern** [comment]
It doesn't look like the label changes at all in this example.

The reason for the blank label is that the label from the `Button("some label")` trait declaration is passed when the trait is asked to give its default editor. Here, you are specifying a `ButtonEditor()`, but not telling the `ButtonEditor()` what the label is.

https://github.com/enthought/traits/blob/master/traits/trait_types.py#L3252

**Comment by rkern** [comment]
If you omit the `style='custom'` to get the `SimpleEditor`, the label won't be `Play` but `Play button`, which is Traits "helpfully" giving you an automatic label from the trait name `play_button`. Arguably, the `CustomEditor` should do the same thing as the `SimpleEditor` in this case, but it's not the behavior you wanted to get.

**Comment by rkern** [comment]
Did you mean to provide an example that uses `label_value=…`?

**Comment by mdickinson** [comment]
> Did you mean to provide an example that uses label_value=…?

Sorry, yes. I had such an example, and then mistakenly decided that the dynamic label text wasn't necessary to demonstrate the issue.

**Comment by mdickinson** [comment]
Better demonstration script:
```
from traits.api import Button, HasTraits, Unicode
from traitsui.api import ButtonEditor, Item, UItem, View

class A(HasTraits):
    play_button = Button("Play")

    play_button_label = Unicode("I'm a play button")

    traits_view = View(
        UItem(
            'play_button',
            editor=ButtonEditor(label_value="play_button_label"),
        ),
        Item('play_button_label'),
        resizable=True,
        style='custom',
    )

if __name__ == '__main__':
    a = A()
    a.configure_traits()
```
