### ISSUE TITLE
Python 3 and wxPython Phoenix backend

### ISSUE THREAD

**Issue by braidedlogix** [enthought/traitsui#356]
For many reasons, I think it is very important for ETS to continue to work under wxPython, and for Python 3 Phoenix is the only option. It has taken several months, but I have set up a branch of ETS that is working for most tests and demos that don't involve QT or Python2-specific tools. I have made no attempts to maintain compatibility with Python 2 or previous versions of wxPython. It took me nearly 6 weeks to track down primary sources of segfaults, and the question of Py2 or Py3 became too much in the context of fixing everything else. It SHOULD be easy enough for others test out this branch using the ets.py version from GitHub braidedlogix/ETS_py3/blob/master/ets.py. I ran yapf on most of the folders, so it would probably be easy enough to run a manual diff against a master branch of a similarly yapf'ed ETS folder to see the changes in the most concise way.

If I could figure out where the actual QT5 stuff is located and what settings and environment variables need to be used, I certainly would have no problems using this external branch to test QT5 with Python 3, without trying to maintain QT4 compatibility. With so many branches and tests, I have no idea where to get the right sources, nor do I have the expertise with QT to figure these out on my own.

As of yesterday, I was still finding buried behaviors that needed fixing (in that case the things required to make the Envisage task examples run). Still, the only persistent annoyance are some rendering flaws for the Mayavi/mlab object windows that sometimes don't render completely under (and only under) Windows 7 (8+ seems fine in my limited testing).  These seem to be entirely due to the extreme depth of nested/embedded panes, as rendering is fine in most cases when moved up to less deep locations (notebook page to dedicated popup for example).

**Comment by corranwebster** [comment]
Thanks for your work. We haven't really had a chance to look at working with Wx Phoenix/4.0, but I agree that keeping support for Wx is an important goal, and while we mostly use Qt here at Enthought now, we still have some projects on Wx.

All of the handling of which Qt API to use is in [`pyface.qt`](https://github.com/enthought/pyface/tree/master/pyface/qt), and current master of TraitsUI should _mostly_ run OK with Qt4 and Qt5 (we still see occasionally segfaults which we haven't tracked down, but our suspicions are on the testing infrastructure, rather than the main body of code).

We want to be careful about supporting multiple codebases in the project, so while we'd love to see PRs to improve support for Wx, we still need to support Python 2.7 (and for the foreseeable future, that will be the primary language of the codebase, since we use 2to3 and don't currently have the bandwidth to get rid of its use).

I'm most familiar with the Pyface/TraitsUI and Enable/Chaco pieces of ETS.  For specific issues about other parts of the ETS stack, such as Mayavi, you might raise specific issues there.

Once again, thanks for your interest and work.

**Comment by braidedlogix** [comment]
I will close this issue quickly, but before doing so I want to summarize the various changes required to make it all work with the main code base.

0. Run an imagemagick convert on all the ets packages to get rid of RGB profile warnings for *.png images.
1. Easy changes that won't break anything, mostly related to event bindings to get rid of warnings
2. Things that would be easy within "if version: else ..." blocks. Some of these may involve changing import locations.
3. Some Python 3 changes that can be handled easily (I know now in retrospect) with six, as RR and others did to maintain py2/3 compatibility within Phoenix.
4. A few nontrivial changes that six or 2to3 don't cover well. 

Most of my time over the past many weeks has been related to finding specific triggers to segfaults, some specific to Py3 and others specific to Phoenix, and then identifying what were usually simple fixes. I think a good intern could run a diff between each of the packages (after running yapf on each) and make these changes over a couple of weeks to create a non-breaking, merge-worthy upgrade. 

My decision to move forward toward Py 3 and Phoenix came soon after suffering the consequences of relying on legacy operating systems and legacy code bases. My experiences would have all been catastrophic had it not been for vast layers of backups, and I would encourage others to modernize with something just shy of a Y2K-level of urgency. 

At this point, under Python 3.6 and wxPython Phoenix, my branch gets through all but a few non-QT tests in all packages, and almost all of the demos in Chaco, TraitsUI,  and Mayavi. There are minor layout issues, some minor issues upstream of ETS, and some minor issues in TVTK for VTK 7.1, but otherwise everything appears highly functional under Python 3. My biggest concerns are potential memory leaks (nothing specific, just a general concern) and the already-noted problem with rendering of deeply-nested windows under Win7, but the branch definitely is a good starting point for Python 3.

**Comment by braidedlogix** [comment]
Thanks for pointing me in the correct direction for qt-related things. My branch has now been updated for qt5 and almost all demos are running with pyqt5 or wxpython backends under Linux, Windows 7, and OSX. Some noteworthy quirks:
     1. Slight differences in PyQt5  implementations (all v5.6, though) required a couple of try/except blocks to catch changes in method names.
     2. Under OSX, the Chaco and TraitUI demos segfault on exit, but virtually all demos run under each without issue, and each individual demo runs fine and exits without segfaults.
     3. On OSX and qt, Mayavi render windows aren't being embedded properly and only take up about a quarter of the window pane.  The problem is in VTK though, not tvtk. I'm studying this a bit.
     4. For all platforms, for the Envisage examples.plugins.tasks.attractors example, traits.trait_handler.TraitInstance does not properly validate a class that is implicitly subclassed through a "provides" decorator. If I disable this validation, the example runs fine for both backends on all operating systems. This behavior will merit a separate issue.

On the whole, the branch takes care of many issues noted in the master branch.

**Comment by corranwebster** [comment]
For number 3, are you on a macbook with a retina display?  If so it could well be that VTK (or possibly Mayavi's Qt component) isn't correctly computing the size?

**Comment by braidedlogix** [comment]
Yes - retina display. Is there a simple patch

**Comment by braidedlogix** [comment]
The inclusion of PyQT5 has provided a wealth of feedback for the various TraitsUI editors, and I am picking off various deficiencies for a number of things. Let me express great gratitude for the demo module and demos in general for providing vast opportunities for comparisons between toolkits. There is almost, but not quite yet, parity between the backends. 

Worth noting is the fact that, at least under Windows 7 where I tested, most of the bad behaviors for pyface.grid-based widgets went away in the latest snapshots for wxpython-phoenix. That said, one snapshot introduced various segfaults that were eliminated in a followup snapshot. Phoenix is mostly fixed, but still something of a moving target, and it may be that minor-buggy behaviors in ETS will go away with upstream changes. I think those small upstream changes provide strong incentives to maintain sandbox status, though.

**Comment by braidedlogix** [comment]
I must leave this effort for a while, but I just wanted to note that almost everything seems to be working properly. Tests under multiple Linux versions, OSX, and Win7, using both QT or wxPython backends, have helped me identify minor issues. I am sure there are many more minor ones, but I wanted to point out three substantial issues that I won't be able to work on for a while:
1.  for wxPython, custom grid cell editors invoked from the GetAttr method cause segfaults immediately after losing focus. The cell widgets work, though nothing works once you attempt to leave the cell. At this point, I disabled the custom editors to make the tables behave properly. I think the problem is upstream, as I have traced it as much as I can through TraitsUI and can't (yet) find any specific things that would cause this. 
2. Under QT, the previously-noted demo segfault-on-exit is due to the HTML engine change in QT5 from QT4. This may have been fixed for QT5.7, but I don't have time to test at this point.
3. For wxPython, rendering html files does not work for the regular wx.html widget. Somehow, the rendering gets hijacked and the widget displays only unrendered or partially rendered text. The underlying widget works fine, so I am unsure about the chain of events that intercept the final product. Changing to the html2 engine (webview) made the problem go away, so this may not matter much except from the standpoint of understanding why this behavior occurs.

As it stands now, though, all the demos for TraitsUI and Chaco that CAN run under a specific backend and Python 3 seem to running

**Comment by yxdragon** [comment]
did you means now we can use mayavi in wxphoenix?  need I clone the newest code and compile myself? I am working on a imageprocessing project based on numpy and wx. [ImagePy](https://github.com/Image-Py/imagepy), just like ImageJ of python. I want to use mayavi as the 3D Viewer, so I need it support wxphoenix.

**Comment by corranwebster** [comment]
WxPhoenix support isn't in master of ETS at this point, but @braidedlogix has forks of the various ETS projects in his github account that you may be able to use.  We'd love a pull-request that adds support, but we can't break compatibility with wxPython 3 at this point, so we need to be able to support both.

**Comment by yxdragon** [comment]
but wxpython 2.8 /3  even python2.7 will be outdated in one or two years, so did you has plan to support wxphoenix? or give up wx? you know, pyqt is in GPL, and wxphoenix are cleaner than 3.0 and with better document. I want to know your plan and timeline if possible. thanks!

**Comment by corranwebster** [comment]
Yep, we have a fair idea of the pros and cons of the different backends.  Right now most of Enthought's clients and internal projects are using Qt with either PySide or PyQt, so we don't have a lot of bandwidth for Wx at the moment (other than the work that Robin Dunn is doing, of course).  We'll happily accept PRs from the community to improve Wx support, of course!

I wrote up a quick overview of the plans for TraitsUI in the ETS-Users google group: https://groups.google.com/forum/#!topic/ets-users/i7wEi52nB9Y

**Comment by yxdragon** [comment]
@braidedlogix I wrote a simple toolkit names myvi, It is not as powerful as mayavi, but esay to install, support wxpython-phoenix. [Myvi](https://github.com/yxdragon/myvi)
