### ISSUE TITLE
FileEditor for qt4 backend: no save file dialog

### ISSUE THREAD

**Issue by pberkes** [enthought/traitsui#37]
The wx backend supports the `dialog_style='save'` option, but the qt4 one does not.
So when creating a Save file... kind of dialog, the user has to select a random file in the desired path, then change the name of the file after exiting the browser.

**Comment by corranwebster** [comment]
Fixed: https://github.com/enthought/traitsui/commit/1b7332d5246cb66f5261595512f1933b9c046637
