### ISSUE TITLE
ListEditor menu not available with PyQt (works with pyside)

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traitsui#374]
The demo `demo/Standard_Editors/ListEditor_demo.py` exposes a menu to move/delete/add nodes in the list when clicking the arrows of the ListEditor when running pyside, but not when running PyQt:

<img width="247" alt="screen shot 2017-06-27 at 12 25 41 pm" src="https://user-images.githubusercontent.com/593945/27601259-4b9f7568-5b34-11e7-95e2-9382bc8c8c38.png">

Seen on both OSX and Windows, under both Python2.7 and Python3.6.

**Comment by corranwebster** [comment]
Is this on current master or the last release?  I made some changes to the `ListEditor` in February, so it is possible that that broke something.

**Comment by jonathanrocher** [comment]
That's not it. My windows tests were made with Canopy/EDM installed traitsui 5.1.0. I can reproduce the issue with current master.

**Comment by corranwebster** [comment]
OK thanks.

**Comment by corranwebster** [comment]
This looks like there is an issue with sending objects via `QSignalMapper`s in PyQt.
