### ISSUE TITLE
Uninformative exception if no toolkit installed

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#390]
When I run a minimal Traits UI application (code below) in an environment that doesn't have any GUI backend installed, I get the following rather uninformative traceback.
```
bash-3.2$ python sem_viewer.py 
Traceback (most recent call last):
  File "sem_viewer.py", line 15, in <module>
    viewer.configure_traits()
  File "/Users/mdickinson/.edm/envs/resist/lib/python2.7/site-packages/traits/has_traits.py", line 2172, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/mdickinson/.edm/envs/resist/lib/python2.7/site-packages/traitsui/toolkit.py", line 291, in view_application
    raise NotImplementedError
NotImplementedError
```
Ideally, the exception should have a message indicating what's wrong.

Here's the code:

```
from traits.api import HasStrictTraits, Unicode
from traitsui.api import Item, View

class Viewer(HasStrictTraits):

    name = Unicode(u"boris")

    def default_traits_view(self):
        return View(
            Item('name'),
        )

if __name__ == '__main__':
    viewer = Viewer()
    viewer.configure_traits()
```

TraitsUI version is 5.1.0

**Comment by corranwebster** [comment]
Agreed, the messaging could be better, but the mental model here is that you have ended up with the `null` toolkit, and it doesn't implement the appropriate methods.  FWIW, Pyface in master gives an error message of the form "the 'null' toolkit doesn't implement <thing>".  Would something similar be suitable in this situation?

**Comment by mdickinson** [comment]
> Would something similar be suitable in this situation?

Sure, that works. Just so there's _some_ hint of what's wrong.
