### ISSUE TITLE
Using ETS_TOOLKIT with qt5 wrappers is confusing

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#407]
In order to dictate that traitsui uses qt5 one needs to set `ETS_TOOLKIT==qt4` and `QT_API==pyqt5` or `QT_API==pyside2`. The value of ETS_TOOLKIT as 'qt4' is confusing in this case. Ideally a value of 'qt5' might make more sense.

**Comment by prabhuramachandran** [comment]
I agree, it would be nicer to have it spelled as qt5 without needing to set the QT_API setting at all.

**Comment by corranwebster** [comment]
Unfortunately the 'qt4' is hard-coded into module names in a number of places throughout ETS.  We can't change it to just "qt" without breaking a whole lot of stuff.  However the entrypoint mechanism introduced for pyface may allow us to do something longer-term, but would require replication throughout the codebase, not just in TraitsUI.

**Comment by itziakos** [comment]
Can we add the `qt5` option?

**Comment by corranwebster** [comment]
No :)  I would much rather have a `qt` option and then use `QT_API` to decide between Qt4 and Qt5 as needed and then gradually deprecate the `qt4` option.

**Comment by itziakos** [comment]
That is fine as long as we have a plan.

**Comment by corranwebster** [comment]
This is now resolved for Pyface and TraitsUI.  However all downstream libraries will also need to be adapted to understand that `qt` is a synonym for `qt4`.

**Comment by corranwebster** [comment]
Closing this for TraitsUI
