### ISSUE TITLE
how can i update image in mayavi scene, when i update my datasoure? 

### ISSUE THREAD

**Issue by vonlippmann** [enthought/traitsui#417]
I use mayavi and traitsUI to build my own application about structure's topology optimization . I set a button in this application .  When i click this button,  the application will run some codes to update the data soure,  so i could see the changing of structure's shape in  every single iteration. However when i click
 the button ，the application will be not responding ，and i will not update the picture ,until all the iteration finished .How can my application be activated, although it is running some other codes ?

**Comment by corranwebster** [comment]
There are two basic ways to keep any GUI application responsive while running time-consuming computations:

- Run the computations in a background thread or background process.  If you do this then you need to be careful that any updates to the UI happen on the UI thread (using the `dispatch="ui"` option with `on_trait_change` helps with this, but there are a number of different strategies).
- Manually process events from the GUI periodically during your computation code (for example, immediately after each iteration where you update the visualization).  The `pyface.gui.GUI` class has [methods for doing this](https://github.com/enthought/pyface/blob/master/pyface/i_gui.py#L134).

The second is probably the most straightforward for your particular case as long as each iteration does not take too long to run.

In sketch form, your code might look like:
```
class TopologyOptimizer(HasTraits):
    gui = Instance(GUI, ())
    data = Any
    iterations = Int
    run = Button()

    def _run_changed(self):
        for i in range(iterations):
            self.data = optimize(self.data)
            self.gui.process_events()
```

This sort of question may be best directed to the ETS-Users mailing list: https://groups.google.com/forum/#!forum/ets-users.

**Comment by vonlippmann** [comment]
Thank you so much , i have tried your first advice, and it really works.
