### ISSUE TITLE
Canopy user unexpected error: AttributeError 'NoneType' object has no attribute 'auto_add' 

### ISSUE THREAD

**Issue by mgrady3** [enthought/traitsui#424]
Moved to a Canopy issue for the time being

**Comment by corranwebster** [comment]
@mgrady3 Yes, possibly related to #174 but hard to tell from context. `self.factory` being `None` is somewhat odd, which means the error is probably occurring during initialization or teardown of the editor.  Did the user describe consequences of the error, or were there just messages in the logfile?

Also, for future reference, this is a public repo, so you should be _very_ careful about posting internal Enthought links or user log files, etc.

**Comment by mgrady3** [comment]
Moving this to a Canopy issue
