### ISSUE TITLE
Checkboxes inside a TableEditor are near-invisible on macOS.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#439]
Here's the result of running `traitsui/examples/demo/Advanced/Table_editor_with_checkbox_column.py` on my machine. The checkboxes are close to invisible.

![screen shot 2018-03-26 at 11 23 32](https://user-images.githubusercontent.com/662003/37901109-2eff674e-30e8-11e8-8cce-078598a53e44.png)

A checkbox rendered outside a table has the expected appearance: here are screenshots from the `traitsui/examples/demo/Standard_Editors/BooleanEditor_demo.py` demo:

![screen shot 2018-03-26 at 11 26 43](https://user-images.githubusercontent.com/662003/37901266-a7003836-30e8-11e8-8992-0e025636c065.png)
![screen shot 2018-03-26 at 11 26 46](https://user-images.githubusercontent.com/662003/37901268-a871718a-30e8-11e8-880b-7de94ca8cc29.png)

Might there be some style setting leaking down from the TableEditor into the child checkboxes?

Versions: TraitsUI 5.1.0, PyFace 5.1.0, PyQt 4.12, Qt 4.8.7, Python 2.7.13, macOS 10.13.3

**Comment by corranwebster** [comment]
I was aware that there was an issue here when testing under PyQt5 (it's even more broken there) - I think that the current code for checkboxes is doing things an old/difficult way when there is now a newer better way provided by Qt using `QStyledItemDelegate`s and the `QCheckStateRole`.  Refactoring to the new way would likely fix it, but is a fair bit of work.

**Comment by stefanoborini** [comment]
PR #456 should fix, however I am realising an additional issue. From the code, the probable outcome of a disabled table is that the checkboxes will appear as enabled anyway.
