### ISSUE TITLE
PySide2 Support

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#452]
The Qt developers have announced formal support for Pyside2 as part of Qt proper, and have started making public wheels available: http://blog.qt.io/blog/2018/04/13/qt-for-python-is-coming-to-a-computer-near-you/

With Pyface 6.0 if you pip install the appropriate wheels referenced above into your Python environment, then you can set the `QTAPI` environment variable to `pyside2` and it may possibly work.

**Comment by rahulporuri** [comment]
closing this issue as PR https://github.com/enthought/traitsui/pull/451 added support for PySide2 (by adding it to the CI matrix) and we've been testing against pyside2 since.
