### ISSUE TITLE
Broken layout when using notebook editor

### ISSUE THREAD

**Issue by danieljfarrell** [enthought/traitsui#459]
# Demostration code

Please see [repo. here](https://github.com/danieljfarrell/traitsui-notebook-resize-bug) for full demo. of this issue.

# The problem

Layout of the application is shown in the screenshot below.

It consists of Document View > (list of) Instrument Views > Measurement View

Note that the document view is using a `ListEditor(use_notebook=True)` so that
the insturments views all appear in their own tabs.

![correct_layout](https://user-images.githubusercontent.com/112847/40049976-155be4c6-582e-11e8-83d3-36713f914846.png)

Adding a new AppView view at the top of the hierarchy breaks the layout.

The new structure is App Vew > Document View > (list of) Instrument Views > Measurement View

![layout_issue](https://user-images.githubusercontent.com/112847/40049982-19345eca-582e-11e8-9c96-ee8b20e69ba1.png)

# Versions

Windows 7, Windows 10, Windows Server 2012 R2
Python 2.7.8
wx 2.8.12.1
traits 4.5.0
traitsui 4.5.1
chaco 4.5.0
enable 4.5.1
kiva 4.5.1
pyface 4.5.2

**Comment by corranwebster** [comment]
I am not seeing this on OS X, TraitsUI and Pyface 5.1, and WxPython 3.0.2 or 2.9.4.  Nor am I seeing it under Qt.  It's non-trivial for me to test this under Windows.

My immediate reaction is to try this under WxPython 3.x and with more recent versions of the ETS tools (ideally TraitsUI 6.0, but at least 5.1).

**Comment by corranwebster** [comment]
Note that even if you are not using Enthought's deployment stack, you can get a test environment up and running very quickly by downloading [EDM](http://docs.enthought.com/edm/) and installing chaco into a clean environment, something like:
```
$ edm install -e test-environment chaco wxpython
$ edm shell -e test-environment
(test-environment)$ python issue_demo.py
```
If this fails for you, then report it here as it will be easy to replicate in other environments.

**Comment by danieljfarrell** [comment]
OK! Will try that. Thanks! We have a legacy application running on the version above. I will have to see how much work is involved in moving it to a new runtime.

**Comment by corranwebster** [comment]
I'm assuming that this was resolved.  If it wasn't please re-open and we can investigate further.

**Comment by danieljfarrell** [comment]
Yes, I think I got around this problem either by updating traits version or by laying out in a different way. Thanks
