### ISSUE TITLE
Python3.6 traits directory and file classes restricted to users folder

### ISSUE THREAD

**Issue by SirJohnFranklin** [enthought/traitsui#467]
Hi,

I already asked this on stackoverflow, but after a little bit of trying I think this is a bug?

Here's the Link:
https://stackoverflow.com/questions/51191096/python3-6-traits-directory-and-file-classes-restricted-to-users-folder

This is the code:
```
import os
from traits.api import (HasTraits, File, Directory)
from traitsui.api import (View, UItem, HGroup)

os.chdir('C:/')

class TestTraitsFile(HasTraits):
    file = File(value='C:/')
    direc = Directory(value='C:/')

    def traits_view(self):
        view = View(
            HGroup(
                UItem('file', style='custom'),
                UItem('direc', style='custom'),
            ),
            resizable=True,
        )
        return view


if __name__ == '__main__':
    obj = TestTraitsFile()
    print("obj.file = ", obj.file)  # 'obj.file = ', 'C:/'
    print("obj.direc = ", obj.direc)  # 'obj.direc = ', 'C:/'
    obj.configure_traits()
    print("obj.file = ", obj.file)  # 'obj.file = ', 'C:/'
    print("obj.direc = ", obj.direc)  # 'obj.direc = ', 'C:/'
```

Using python 2.7, everything is fine but when I switch to python 3.6, the file browsers are limited to the users folder.

Picture python2.7: [p2.7](https://i.stack.imgur.com/gHZJq.png)
Picture python3.6: [p3.6](https://i.stack.imgur.com/7wTzw.png)

Do you have an idea why this is different?

Best,
SJF

**Comment by corranwebster** [comment]
That certainly seems like a problem: can you tell me which release of TraitsUI you are using, and which backend toolkits you are using in each case (ie. WxPython vs PySide vs. PyQt4 vs. PyQt5)?

**Comment by SirJohnFranklin** [comment]
With: 
```
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'wx'
```
it is working.

With:
`ETSConfig.toolkit = 'qt4'`
it won't work.

Versions:
```
traits.__version__ =  4.6.0
traitsui.__version__ =  6.0.0
```

Since PySide is not available for python 3.6 it does not affect the error or am I mistaken?

Best,
SJF

**Comment by corranwebster** [comment]
Thanks.  This could possibly be a fundamental difference between the behaviour of Qt and Wx or it could be a difference between the editor implementations in TraitsUI. I'll have a look into it.

There is experimental support for PySide2 in the 6.0.0 release.  We don't have wxPython 4.0 support yet, so no Python 3 + Wx at the moment, unfortunately.

**Comment by SirJohnFranklin** [comment]
I have an update:
Downgrading traitsui to version 5.1.0 and changing "setResizeMode" to "setSectionResizeMode" on line 217 in file_editor.py lets traits start and shows normal behaviour.

Best,
SJF

**Comment by corranwebster** [comment]
Looking in to this, it appears that PySide and PyQt report Qt versions differently.  I am adding a more definite check in Pyface which can then be used in TraitsUI.

**Comment by corranwebster** [comment]
Looking into this more, this was a deliberate change in behaviour in 6.0.0.  There is an easy work-around which is to set the `root_path` of the editor:
```
UItem('file', style='custom', editor=FileEditor(root_path='/'))
```
or if you need to set the root path dynamically from a trait value you can use `root_path_name` instead.

I think this addresses the issue, so I'm going to close it.
