### ISSUE TITLE
Remove "Specifies" when rendering a tooltip

### ISSUE THREAD

**Issue by prabhuramachandran** [enthought/traitsui#472]
Traitsui automatically adds "Specifies" to the tooltip when a `desc` is added to a trait definition.  This is not configurable and can be painful sometimes. Could this be removed or at least made configurable?

**Comment by rkern** [comment]
Safest and easiest would be to use another metadata keyword that, ahem, specifies the complete string that you want to use and soft-deprecate `desc`. When the new keyword is not `None`, then it will be used, and `desc` will be ignored; otherwise, `'Specifies ' + desc` will be used.

**Comment by prabhuramachandran** [comment]
Sounds good to me, what should this be?  `tooltip`?

**Comment by rkern** [comment]
Yes, I believe that would be appropriate.

**Comment by prabhuramachandran** [comment]
Sent a PR for this in #473.

**Comment by prabhuramachandran** [comment]
Closing as #473 is merged.
