### ISSUE TITLE
2 issues with RangeTextEditor

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traitsui#480]
RangeTextEditor ends up being used for integer values over a large range, which I am guessing means it isn't used much. I am finding 2 issues with it:
1. It ignores the `auto_set` factory attribute, maybe others as well.
2. It issues an AttributeError on close of the editor:
```
Traceback (most recent call last):
  File "/Users/jrocher/.edm/envs/**_dev_py27/lib/python2.7/site-packages/traitsui/qt4/range_editor.py", line 781, in update_object
    pal = QtGui.QPalette(self.control.palette())
AttributeError: 'NoneType' object has no attribute 'palette'
```

**Comment by corranwebster** [comment]
I think that the first issue will be resolved by #535.
