### ISSUE TITLE
ProgressEditor fails in Qt

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#487]
Currently this assumes the presence of a private method `_create_percent` which is not present in the Pyface Qt backend, and which is not implemented in the Pyface Wx bacakend.

Traceback:
```
Traceback (most recent call last):
.
.
.
  File "/Users/cwebster/.edm/envs/resist-py27/lib/python2.7/site-packages/traitsui/qt4/progress_editor.py", line 72, in create_control
    self.progress._create_percent(control, layout)
AttributeError: '_ProgressDialog' object has no attribute '_create_percent'
```

**Comment by danieljfarrell** [comment]
Just came across this and was about to write an issue.

What's the fix here? What is `_create_percent` intended to do?

    from traits.api import HasTraits, Int, Button
    from traitsui.api import Item, View
    from traitsui.editors import ProgressEditor


    class App(HasTraits):
        """ Demo. of progress editor.
        """
        percentage_complete = Int(0)

        view = View(
                Item('percentage_complete',
                     show_label=False,
                     editor=ProgressEditor(min=0, max=100)
                     ),
                Item('start_task_btn', show_label=False),
                resizable=True
                )


    if __name__ == '__main__':
        app = App()
        app.configure_traits()

**Comment by serwy** [comment]
When using the `wx` backend (version '3.0.2.0') you'll get
  ```

File "/Users/rserwy/.edm/envs/rds27/lib/python2.7/site-packages/traitsui/wx/progress_editor.py", line 67, in create_control
    panel.SetBackgroundColour(wx.NullColor)
AttributeError: 'module' object has no attribute 'NullColor'
    
```

**Comment by serwy** [comment]
The merged PR in pyface resolves this issue.

**Comment by danieljfarrell** [comment]
Great! Thanks so much. I will give it a go.

When is the next release planned?
