### ISSUE TITLE
Tree node get children method should handle nested trait names

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#491]
The [`get_children`](https://github.com/enthought/traitsui/blob/193898594c85ad612b8b7ab9815bc810ace466f8/traitsui/tree_node.py#L219-L222) method uses the standard `getattr` rather than `traits.trait_base.xgetattr`, and so nested trait names cannot be used as children.

**Comment by rkern** [comment]
That should be feasible. Just be sure to replace the other instances of `getattr(object, self.children)` with `self.get_children(object)`. The other use of `self.children` is to set up dynamic `object.on_trait_change()` handlers on `self.children` and `self.children + '_items'`, but those will consume dotted attr chains just as well.
