### ISSUE TITLE
Classic integer divisions in qt4/toolkit.py, qt4/ui_panel.py.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#495]
There are some uses of int/int division in qt4/toolkit.py, and qt4/ui_panel.py. I'd fix them, but it's not clear to me whether the intended behaviour is actually floor division or whether it's true division.

Two cases in this block:

https://github.com/enthought/traitsui/blob/193898594c85ad612b8b7ab9815bc810ace466f8/traitsui/qt4/toolkit.py#L278-L298

One case here (for this one, it's clearer what the intended semantics are):

https://github.com/enthought/traitsui/blob/193898594c85ad612b8b7ab9815bc810ace466f8/traitsui/qt4/ui_panel.py#L468

We encountered these while running the test suite for a TraitsUI-using application on Python 2 under `-Qwarn`; if nothing else, it would be helpful to have them cleaned up in Traits UI just to avoid the false positives.

**Comment by corranwebster** [comment]
Looking at these, I think they probably could both be switched to truediv without any problem.
