### ISSUE TITLE
Using view(kind='wizard') raises ModuleNotFoundError

### ISSUE THREAD

**Issue by danieljfarrell** [enthought/traitsui#507]
Do you have an example which shows how to string together a sequence of views without using the wizard option? 

Running the following code raises a ModuleNotFoundError.

The relevant packages in my python environment are,
```
pyface                    6.0.0                    py37_0
pyqt                      5.9.2            py37h6538335_2
pytest                    4.1.1                    py37_0
python                    3.7.2                h8c8aaf0_0
qt                        5.9.7            vc14h73c81de_0
traits                    4.6.0            py37hfa6e2cd_3
traitsui                  6.0.0                    py37_1
```

Here is a minal script that reproduces the error,

```python
from traits.api import HasTraits, Str

class Person(HasTraits):
    first_name = Str('')
    last_name = Str('')

def main():
    person = Person(first_name='Postman', last_name='Pat')
    person.configure_traits(kind='wizard')

if __name__ == '__main__':
    main()

```

The error,

```
Traceback (most recent call last):
  File "wizard_example_simple.py", line 16, in <module>
    main()
  File "wizard_example_simple.py", line 13, in main
    person.configure_traits(kind='wizard')
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traits\has_traits.py", line 2171, in configure_traits
    kind, handler, id, scrollable, args )
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\qt4\toolkit.py", line 222, in view_application
    id, scrollable, args)
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\qt4\view_application.py", line 84, in view_application
    scrollable, args).ui.result
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\qt4\view_application.py", line 136, in __init__
    args=self.args)
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\view.py", line 448, in ui
    ui.ui(parent, kind)
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\traitsui\qt4\toolkit.py", line 184, in ui_wizard
    import ui_wizard
ModuleNotFoundError: No module named 'ui_wizard'
```

**Comment by jonathanrocher** [comment]
It seems like that's only supported on WX, not Qt (at least for now). If I set `ETS_TOOLKIT=wx`, and if you break your view into groups like this:
```
from traits.api import HasTraits, Str
from traitsui.api import Item, View, VGroup

class Person(HasTraits):
    first_name = Str('')
    last_name = Str('')

    view = View(
        VGroup(Item("first_name")),
        VGroup(Item("last_name"))
    )
```
you would get the following series of views:
![screen shot 2019-02-28 at 10 41 36 am](https://user-images.githubusercontent.com/593945/53582659-82844700-3b45-11e9-9ffd-97844f11eb68.png)
![screen shot 2019-02-28 at 10 41 47 am](https://user-images.githubusercontent.com/593945/53582660-82844700-3b45-11e9-9f93-4ee16f6fc5ae.png)

TODO: 
* the documentation page that talks about this doesn't have any example code
* the only example that mentions wizard doesn't show anything: https://github.com/enthought/traitsui/blob/master/examples/tutorials/doc_examples/examples/wizard.py

**Comment by danieljfarrell** [comment]
Thanks, that explains how to use it. I can’t move from the QT backend. 

How could I replicate this on QT? Maybe just using command buttons (eg Next and Back) and replacing the view?

**Comment by jonathanrocher** [comment]
I would reproduce the behavior using:
- an overall class to manage the whole thing and keep track of what to display next,
- different view classes using custom buttons (`Back`, `Next`, `Finish`), opened using `edit_traits(kind="livemodal")`,
- handlers to implement what to do with these buttons.

Good luck!

Ps To ask questions, instead of creating issues, I would recommend you join the ETS mailing list: https://groups.google.com/forum/#!forum/ets-users

**Comment by danieljfarrell** [comment]
OK, I’ll probably post something on the forum later. Want to keep this open as a bug report?

**Comment by corranwebster** [comment]
The easiest way to do this on Qt is to have an `Instance` trait to hold the page with a `style='custom'` `Item` and hidden label in the `View` and left and right buttons, as you suggest.  You'd also want a little logic about whether you are at the first or last page so you can have appropriate `enabled_when` for the buttons.

I don't think there is an example of this exact patterm.

**Comment by danieljfarrell** [comment]
OK, I think I have a good idea of how to implement that now. I'll update this issue when I manage to look into it further.
