### ISSUE TITLE
Disposal of UI.key_bindings creates a KeyBindings object

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#523]
There's something odd in the way that `UI.key_bindings` is handled. In the `UI.finish()` method (called by the `UI.dispose()` method), we have the [following lines](https://github.com/enthought/traitsui/blob/8302d8a09f3c05798ff588c3e6f46634d7ae1613/traitsui/ui.py#L299-L300):
```
        if self.key_bindings is not None:
            self.key_bindings.dispose()
```
But `key_bindings` is a property, and accessing that property creates a _new_ `KeyBindings` object (which may be completely new, or may be a clone of an existing object).

Given that `_get_key_bindings` appears to return a new `KeyBindings` object every time, what's the correct way to clean up all those objects?

**Comment by mdickinson** [comment]
Diving into the history, commit https://github.com/enthought/traitsui/commit/3346d07e6ff5d16a5ad53f132203c16075e818f6 looks relevant: it looks as though `key_bindings` was changed to a `Property` from a concrete data trait, and at that point the existing cleanup logic likely stopped making sense.

**Comment by corranwebster** [comment]
Probably the best way to do it if keeping the `Property` nature is desirable is to use a private shadowing trait:
```
key_bindings = Property(Instance(KeyBindings), depends_on=['view.key_bindings', 'context'])
_key_bindings = Instance(KeyBindings)
```
and then do something like:
```
@cached_property
def _get_key_bindings(self):
    if self._key_bindings is not None:
        self._key_bindings.dispose()
    ... # do stuff to create new key_bindings
    self._key_bindings = key_bindings
    return key_bindings
```
This should guarantee:

- one copy of the `KeyBinding` object
- it is disposed when it is done with

If clever, you may be able to do this directly with the `cached_property`'s cache (I can never remember what the mangled name is), but that is dependent on knowing how cached properties work, so it potentially fragile.

**Comment by mdickinson** [comment]
Confirmed that this fixes the relevant part of the project issue that triggered my bug report.

LGTM.
