### ISSUE TITLE
Enum ListEditor: Python3 unicode NameError

### ISSUE THREAD

**Issue by wintermute2048** [enthought/traitsui#571]
Running the Enum demo ( https://github.com/enthought/traitsui/blob/master/examples/demo/Standard_Editors/EnumEditor_demo.py ) with python3 and pyside2 gives an error, because 'unicode' in file https://github.com/enthought/traitsui/blob/master/traitsui/qt4/enum_editor.py, line 455 is not defined.

I modified the example to use pyside2 with
```
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
os.environ['QT_API'] = 'pyside2'
```
before the imports.

I haven't worked with 'six' yet, but I assume that 'unicode' should be replaced with 'six.text_type' to fix this.

A workaround is, to add to my script:
```
import sys
import builtins
if sys.version_info[0] >= 3:
    builtins.unicode = str
```

This is my first day on github, please tell me if I do something wrong!

**Comment by corranwebster** [comment]
Thanks for the report.  You are correct that it should likely be `six.text_type`.
