### ISSUE TITLE
ImportError due to circular imports 

### ISSUE THREAD

**Issue by pbrod** [enthought/traitsui#575]
In python I get the following error when I try to import traitsui.table_filter:

    In [2]: import traitsui.table_filter
    
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-86d609b5bc59> in <module>
    ----> 1 import traitsui.table_filter
    
    C:\python\anaconda3\lib\site-packages\traitsui\table_filter.py in <module>
         39
         40 from .editor_factory import EditorFactory
    ---> 41 from .editors.api import EnumEditor
         42 from .group import Group
         43 from .include import Include
    
    C:\python\anaconda3\lib\site-packages\traitsui\editors\__init__.py in <module>
         25     pass
         26
    ---> 27 from .api import (
         28     toolkit,
         29     BooleanEditor,
    
    C:\python\anaconda3\lib\site-packages\traitsui\editors\api.py in <module>
         48 from .set_editor import SetEditor
         49 from .text_editor import TextEditor
    ---> 50 from .table_editor import TableEditor
         51 from .time_editor import TimeEditor
         52 from .title_editor import TitleEditor
    
    C:\python\anaconda3\lib\site-packages\traitsui\editors\table_editor.py in <modul
    e>
         50 from ..item import Item
         51
    ---> 52 from ..table_filter import TableFilter
         53
         54 from ..ui_traits import AView
    
    ImportError: cannot import name 'TableFilter' from 'traitsui.table_filter' (C:\python\anaconda3\lib\site-packages\traitsui\table_filter.py)

The reason for this error is that when I import traitsui.table_filter first, it imports traitsui.editors.api which again import traitsui.editors.table_editor which again import traitsui.table_filter which obviously is a circular import.
However, when I first import traitsui.api and then import traitsui.table_filter I get no error.

**Comment by rahulporuri** [comment]
I am able to reproduce this issue on current master. I think, one of the recommendations is to always import from `traitsui.api` for all of your needs but that doesn't mean that we don't prevent circular dependencies.

```
>>> import traitsui.table_filter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\rporuri\work\github\ets\traitsui\traitsui\table_filter.py", line 38, in <module>
    from .editors.api import EnumEditor
  File "c:\users\rporuri\work\github\ets\traitsui\traitsui\editors\__init__.py", line 26, in <module>
    from .api import (
  File "c:\users\rporuri\work\github\ets\traitsui\traitsui\editors\api.py", line 51, in <module>
    from .table_editor import TableEditor
  File "c:\users\rporuri\work\github\ets\traitsui\traitsui\editors\table_editor.py", line 43, in <module>
    from ..table_filter import TableFilter
ImportError: cannot import name 'TableFilter'
>>>
```
