### ISSUE TITLE
Copy/pasting a tree node doesn't copy

### ISSUE THREAD

**Issue by prabhuramachandran** [enthought/traitsui#578]
I don't have a minimal example but see this with Mayavi's tree editor.  Basically when we copy and paste a node, it doesn't copy the object it but uses the same node.  I think in the changes to the tree editor code this was missed out.  Basically the copy just keeps a reference to the node but when the node is inserted make_copy=False and so it doesn't deep copy the item.

**Comment by corranwebster** [comment]
I'm having a hard time testing this as I am getting lots of exceptions when interacting with the `TreeEditor` (eg. infinite recursion when trying to copy a tree node).

**Comment by prabhuramachandran** [comment]
Is this specifically with Mayavi? Could you please try with Mayavi from master?  I fixed an issue with copying a node a week or so ago.  Thanks so much for testing!

**Comment by corranwebster** [comment]
Ah - no I was using the most recent EDM release.  I'll try again from master.
