### ISSUE TITLE
Search non-functional in published documentation

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#583]
The "Quick Search" box doesn't work in the documentation currently published to [docs.enthought.com/traitsui](https://docs.enthought.com/traitsui): if you enter a search term and press enter, you're taken to a new Search page and no results are displayed.

Rebuilding the documentation with the latest release of the Enthought Sphinx Theme should fix this.

See also enthought/pyface#423.

**Comment by kitchoi** [comment]
From offline discussion: we will try to fix the search functionality as part of the next bug fix release.

**Comment by kitchoi** [comment]
If all this takes is just rebuilding the doc, this issue can also be closed independently of the next release. Adding it to the milestone so this does not get lost.

**Comment by kitchoi** [comment]
The current behaviour does show something, but the "Searching..." (in progress) state never finishes. 

E.g. https://docs.enthought.com/traitsui/search.html?q=tabulareditor

I think we expect a few more sections to show up and that we get a "Search finished" state with the number of found results.

**Comment by mdickinson** [comment]
> Rebuilding the documentation with the latest release of the Enthought Sphinx Theme should fix this.

There has actually been a rebuild since I wrote that line in the original description, but there hasn't been one since the most recent round of updates to the Enthought Sphinx Theme.

IOW, when I wrote that, it wasn't actually true. But now I believe it should be: it should be enough just to rebuild using the latest Enthought Sphinx Theme.

**Comment by mdickinson** [comment]
Related: https://github.com/enthought/enthought-sphinx-theme/pull/12

**Comment by kitchoi** [comment]
Closed via #1004
