### ISSUE TITLE
Item has_focus attribute not respected/no effect

### ISSUE THREAD

**Issue by mgrady3** [enthought/traitsui#599]
In the minimal example below, using the `has_focus` attribute of an Item in a View seems to have no effect with PyQt4 on macOS using Python 2.7

```
from traits.api import HasTraits, Int, Unicode
from traitsui.api import View, Item, VGroup


class TestModel(HasTraits):
    a = Int
    b = Unicode


main_view = View(
    VGroup(
        Item('object.a', has_focus=False),
        Item('object.b', has_focus=True)
    ),
    title="Test Focus"
)

t = TestModel(a=5, b="apples")
t.configure_traits(view=main_view)
```

Running the code above results in the `a` trait's editor getting focus even though the `has_focus` for that Item is set to False.

I have not tested on other python versions or with Qt5

**Comment by corranwebster** [comment]
I've investigated this a bit and the basic problem seems to be that focus is being set too early in the process.  If I tuck away the control that we want to use and the call `setFocus` immediately before we show the window, it works as expected.

Main obstacle to a fix is finding a not-horrible way to pass the focus widget back up to the top-level.

**Comment by mgrady3** [comment]
After reworking the main logic in my UI I no longer need to use this feature - so if the fix will be difficult it can suffice to leave this as a known issue for the time being,  to be fixed later on.

**Comment by mgrady3** [comment]
Also, thanks for the investigation, BTW!
