### ISSUE TITLE
View's icon trait should be an Image, not Any

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#600]
The `icon` trait of a `View` is currently defined as `Any` but using code expects the value to hold an `ImageResource`.  The trait should probably be modified to be an `Image` trait so that it accepts both image names and image resources.

**Comment by rahulporuri** [comment]
Note that there's already a commented out `icon_trait` https://github.com/enthought/traitsui/blob/9261d1fb524845d1031d609db004ab251669919a/traitsui/view.py#L87-L89 that can be used, with relevant modifications.

**Comment by corranwebster** [comment]
Yep, I saw that, but an `Image` trait is better than `Instance` in this situation, I think.  There's also a question of _why_ it was commented out, but that is secondary.
