### ISSUE TITLE
RangeEditor needs to handle invalid model values better

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#632]
It is possible that the underlying value being displayed by a `RangeEditor` is legitimately holding a non-numeric value (eg. see the `CompoundEditor` demo).  Currently the logic around handling changes of the value to an invalid quantity don't work well.

This is probably just a matter of putting better exception handling on the various `update` methods on the editor.

Both backends are bad, just in different ways.

**Comment by sandhya-sago** [comment]
Corran, I do not see any error for QT.
