### ISSUE TITLE
Different API for PyQt5 in tabular editor

### ISSUE THREAD

**Issue by jvkersch** [enthought/traitsui#670]
PyQt5 replaced `QHeaderView.setResizeMode` by  `QHeaderView.setSectionResizeMode`.

What is the best way of incorporating this in the code for tabular editor? Is it OK to have a conditional `if is_qt5:`, or is there a compatibility layer that takes care of this sort of thing?

```
$ git diff
diff --git a/traitsui/qt4/tabular_editor.py b/traitsui/qt4/tabular_editor.py
index 7fb362f5..7d0a8066 100644
--- a/traitsui/qt4/tabular_editor.py
+++ b/traitsui/qt4/tabular_editor.py
@@ -715,7 +715,8 @@ class _TableView(QtGui.QTableView):
             vheader.hide()
 
         if factory.show_row_titles and factory.auto_resize_rows:
-            vheader.setResizeMode(QtGui.QHeaderView.ResizeToContents)
+            # vheader.setResizeMode(QtGui.QHeaderView.ResizeToContents)
+            vheader.setSectionResizeMode(QtGui.QHeaderView.ResizeToContents)
         else:
             # Set a default height for rows. Although setting the resize mode to
             # ResizeToContents would provide the best sizes, this is far too
```

**Comment by mdickinson** [comment]
This is really about Qt 5 / Qt 4 rather than PyQt, right?

But I'm confused. The `setResizeMode` still exists in Qt 5: https://doc.qt.io/qt-5/qheaderview-obsolete.html#setResizeMode

**Comment by mdickinson** [comment]
Ah, right; it's considered obsolete.

**Comment by corranwebster** [comment]
It's Ok to have occasional branches of qt5 vs. qt4 where the API is different (or, for that matter PyQt vs. PySide).  The `pyface.qt` module now provides convenience constants for these tests that make the code somewhat nicer.

**Comment by rahulporuri** [comment]
> ... https://doc.qt.io/qt-5/qheaderview-obsolete.html#setResizeMode

^ link is broken. here's one from web archive which works - https://web.archive.org/web/20190201210020/http://doc.qt.io:80/qt-5/qheaderview-obsolete.html
