### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by coreysharris** [enthought/traitsui#679]
I think this is the same problem as https://github.com/enthought/traits/issues/487 since
```
    <script type="text/javascript" src="_static/searchtools.js"></script>
```
is also missing here.

See https://docs.enthought.com/traitsui/search.html?q=view for an example of the issue.

**Comment by rahulporuri** [comment]
closing as a duplicate of https://github.com/enthought/traitsui/issues/583 which also got fixed with the 7.0.1 release
