### ISSUE TITLE
ShellEditor + NumPy

### ISSUE THREAD

**Issue by fred4ets** [enthought/traitsui#701]
Hi there,

I use ShellPython to run Python commands in my app.
Works well.

BTW, as I often (to not say always) need and use NumPy functions, I wonder how it would be possible to import automatically NumPy when I launch ShellEditor.

Thanks in advance.

Cheers

**Comment by corranwebster** [comment]
The `ShellEditor` can be run on a dictionary which can contain whatever variables you like, including imported modules, so something like:
```
import numpy
from traits.api import Any, Dict, HasTraits, Str
from traitsui.api import View, Item, ShellEditor

class NumpyShell(HasTraits):
    namespace = Dict(Str, Any)
    view = View(Item('namespace', editor=ShellEditor(share=True)))

if __name__ == '__main__':
    ns = NumpyShell(namespace={'numpy': numpy})
    ns.configure_traits()
```

This will make `numpy` available in the namespace.  If you prefer to use `np` you would set `namespace` to `{'np': numpy}`.

There are ways to trigger commands to be run inside the shell, so you could run an actual `import` command, but they would be tricky to get right for that use case.

**Comment by fred4ets** [comment]
Thanks for your prompt answer, works fine.

BTW, would it be possible to call array() without typing np before?

For instance, I would like to type:

a = array([1,2,3])

instead of

a = np.array([1,2 3])

Thanks in advance.

**Comment by rkern** [comment]
`namespace = {'np': numpy, 'array': numpy.array}`

**Comment by fred4ets** [comment]
OK.
I was meaning all NumPy funcs, talking about array.

So I understand (?) it's not possible.

No worries.


Thanks.

**Comment by corranwebster** [comment]
No, it's absolutely possible, just a little trickier (I think your second question wasn't clear).  You are wanting to effectively do an implicit `from numpy import *`?

You just need to populate the namespace with the `numpy` module names.  There are a couple of ways to do it, but the most straightforward is just to do something like:
```
namespace = {}
exec("from numpy import *", namespace, namespace)
ns = NumpyShell(namespace=namespace)
ns.configure_traits()
```

**Comment by fred4ets** [comment]
Le 23/12/2019 à 10:35, Corran Webster a écrit :
> No, it's absolutely possible, just a little trickier (I think your 
> second question wasn't clear). You are wanting to effectively do an 
> implicit |from numpy import *|?
> 
> You just need to populate the namespace with the |numpy| module names. 
> There are a couple of ways to do it, but the most straightforward is 
> just to do something like:
> 
> |namespace = {} exec("from numpy import *", namespace, namespace) ns = 
> NumpyShell(namespace=namespace) ns.configure_traits() |
Mmh, it seems I have did not see your answer, last year.

Thanks a lot, that does exactly what I want.

Regards
