### ISSUE TITLE
Changing the selected row in a TableEditor doesn't redraw correctly

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/traitsui#717]
On Linux (Ubuntu 16.04), this happens with PyQt4 and PyQt5.

(Testing on Mac underway)

Selecting a row in the `TableEditor` with a mouse click works as expected. However, if the trait that is linked to the "`selected`" attribute of a `TableEditor` is changed programmatically, the redraw is partial (triggering the redraw by, for instance, using the scrollbar, fixes the issue).

![Peek 2020-01-13 15-09](https://user-images.githubusercontent.com/7642150/72266707-d4777380-3616-11ea-9b67-0e19af1c2719.gif)

This example:
```python
import random

from traits.api import (
    HasTraits, HasStrictTraits, List, Int, Regex, Str, Button, Instance,
    Property)
from traitsui.api import VGroup, UItem, View, TableEditor
from traitsui.table_column import ObjectColumn


class Employee(HasTraits):
    eid = Int
    first_name = Str
    last_name = Str
    age = Int
    phone = Regex(value='000-0000', regex=r'\d\d\d[-]\d\d\d\d')


class Department(HasStrictTraits):

    employees = List(Employee)
    selected = Instance(Employee)
    random_select = Button()
    this_employee = Property(depends_on="selected")

    def _random_select_changed(self):
        self.selected = random.choice(self.employees)
    
    def _get_this_employee(self):
        empl = self.selected
        if empl is not None:
            return f"{empl.eid}) {empl.first_name} {empl.last_name}"
        else:
            return ""

    traits_view = View(
        VGroup(
            UItem('random_select'),
            UItem(
                'employees',
                editor=TableEditor(
                    columns=[
                        ObjectColumn(name='eid', editable=False),
                        ObjectColumn(name='first_name', editable=False),
                        ObjectColumn(name='last_name', editable=False),
                        ObjectColumn(name='age', editable=False),
                        ObjectColumn(name='phone', editable=False),
                    ],
                    selected="selected",
                )),
            UItem("this_employee", style="readonly")
        )
    )


demo = Department(employees=[
    Employee(
        eid=i,
        first_name=random.choice(["Ada", "Bob", "Claire", "Damian", "Elisa"]),
        last_name=random.choice(["Fitz", "Griffin", "Hack", "Iba", "Jordan"]),
        age=random.randrange(18, 112),
        phone="{0:03d}-{0:04d}".format(
            random.randrange(999), random.randrange(9999))
    ) for i in range(14)
])

if __name__ == '__main__':
    demo.configure_traits()

```

**Comment by nicolasap-dm** [comment]
Issue reproduced on MacOS 10.13, with PyQt4 and PyQt5. The only difference being that on PyQt4 sometimes even scrolling the view doesn't fix the issue.

Details on the packages:
- pyqt 4.12.1 with qt 4.8.7
- pyqt5 5.7.1 with qt 5.6.2
- traitsui master

**Comment by robertopreste** [comment]
Funny thing on macOS with pyqt5 5.7.1 and qt 5.6.2: if I make the view `resizable` and increase its size, only the first cell of the selected row is highlighted, and of course there is no way to scroll to get the selection updated.

![Jan-14-2020 08-51-31](https://user-images.githubusercontent.com/16542755/72328625-2964c980-36ab-11ea-9373-8f7a113e58cf.gif)

If I reduce its height to make it scrollable again, it goes back to **sometimes** highlighting the whole row, some other times just the first cell.
