### ISSUE TITLE
test_color_column fails on wxpython 4

### ISSUE THREAD

**Issue by pbrod** [enthought/traitsui#755]
The test_color_column.py fails using Python 3.7.4, pyface 6.2.0.dev13, traits 6.1.0.dev1423 and wxpython 4.0.7.post2
I guess it is related to issue #752

The error message returned from that failing test is:

> File "C:\Users\tombr\Documents\workspace\git_traitsui\traitsui\wx\table_editor.py", line 478, in dispose
    self.grid.dispose()
  File "c:\users\tombr\documents\workspace\git_pyface\pyface\ui\wx\grid\grid.py", line 416, in dispose
    grid.Destroy()
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

> 

The reason for this error is that the
wx.lib.gridmovers.GridRowMover.lwin.GetEventHandler() returns traitsui.wx.toolkit.EventHandlerWrapper object instead of an wx.lib.gridmovers.GridRowMover object inside the grid.Destroy() method.

**Comment by corranwebster** [comment]
Thanks for the report - wxpython 4 support is currently in development and issues are expected - in particular the test suite is known not to be passing.

If you need to use wxpython please use the last release and wxpython 3.

**Comment by pbrod** [comment]
Yes I know, but I would like to use traitsui, wxpython on python 3.

**Comment by corranwebster** [comment]
The wx backend is currently a spare-time/weekend effort by myself as we are mainly using Qt here.   If you think you have a fix for the issue (which actually looks like it might be in Pyface), then a PR would be welcome if you have time.

**Comment by pbrod** [comment]
Sure, I will look into it and try to find a fix.

**Comment by pbrod** [comment]
The main reason for this failure is due to the faulty value returned from the calls to the static
function "control.FindWindowByName(name)".
From the documentation it will start the search from the top-level frames and dialog boxes and may therefore return the wrong window.
If instead one replaces that call  with "control.FindWindowByName(name, control)", the search will be limited to the given window hierarchy and the correct window will be returned..

**Comment by pbrod** [comment]
For later reference the documentation of wx.Window.FindWindowByName may be found [here](https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.FindWindowByName)
