### ISSUE TITLE
CheckListEditor fails with mixed types

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#757]
How to handle mixed type lists with the check list editor is unclear.

### Example:
```python
from traits.api import *
from traitsui.api import *

class Foo(HasTraits):
    items = List([1, 'two'])
    selected = List
    
    traits_view = View(
        Item('selected', style='custom',
             editor=CheckListEditor(name='items'))
    )

foo = Foo()
foo.configure_traits()
print(foo.selected)
```
fails with:
```
.../traitsui/qt4/check_list_editor.py", line 48, in <lambda>
    capitalize = lambda s: s.capitalize()
AttributeError: 'int' object has no attribute 'capitalize'
```
which is apparently simply [due to the fact that the first element is stringy](https://github.com/enthought/traitsui/blob/277bd2a93006ab4d7a02e9ad6024bab190681976/traitsui/qt4/check_list_editor.py#L80).

If instead the `items` is defined like, e.g., `items = List([1, 'two'])`, then a different failure is observed:
```
.../traitsui/qt4/check_list_editor.py", line 101, in <listcomp>
    self.values = valid_values = [x[0] for x in values]
TypeError: 'int' object is not subscriptable
```
since it is assumed that `values[0] != string type` => `values == list of (value, name)`, but which is not the case.

It seems like this could be a straightforward fix in `traitsui/qt4/check_list_editor.py` by first checking if all the elements are not a tuple, then checking whether all the elements are stringy. If neither are the case, then I think we could recast `values`. Something like
```python
if not all(is_value_name_pair(v) for v in values):
    values = [(v, capitalize(sv(v))) for v in values]
```
where
```python
def is_value_name_pair(item):
    return (isinstance(item, tuple) and
            len(item) == 2 and
            isinstance(item[1], six.string_types)
```

**Comment by corranwebster** [comment]
Yep - looks like something that could do with a re-work; using a `format_func` in the editor factory doesn't help.  It is essentially the same code in both Qt and Wx, so any fix should be in both places.

**Comment by midhun-pm** [comment]
As per the documentation [CheckListEditor](https://docs.enthought.com/traitsui/traitsui_user_manual/factories_basic.html#checklisteditor) can have a value which is either :
 A list of strings OR 
A list of tuples of the form (element, label), where element can be of any type and label is a string.

Since the code works fine when `items = List([(1, 'two')])`
Isn't it enough to raise an error if the supplied value is incorrect ?

**Comment by notmatthancock** [comment]
> As per the documentation ...

Is this documented anywhere other than the user manual? I don't see it specified in the class definition of `CheckListEditor` or `EditorWithListFactory`.

**Comment by rkern** [comment]
The user manual is where the main documentation effort for Traits UI went into and should be high on the list of places to look for information.

**Comment by notmatthancock** [comment]
What's the conclusion? Close this and read the docs better?

**Comment by rkern** [comment]
This issue per se, probably. `CheckListEditor` is working as designed and documented. The current semantics for mapping model objects to labels isn't the most comfortable, so there's room for an addition to TraitsUI that provides a better one. But it might be better to do that in a new `Editor` with some more deliberate design. Or in `qt_binder`.

**Comment by rkern** [comment]
In particular, such a redesign should be coordinated with all of the other `EditorWithList` editors that share the same list-processing semantics. These _are_ in need of an overhaul, and would be a good target for new ETS development. It's just a broader target.
