### ISSUE TITLE
wx_embedding.py fails

### ISSUE THREAD

**Issue by savantas** [enthought/traitsui#760]
Using the latest versions of the involved libraries (traits: 6.0.0, traitsui: 6.1.3, mayavi: 4.7.1, envisage: 4.9.2, vtk: 8.1.2, wx: 4.0.1), the example wx_embedding.py (http://docs.enthought.com/mayavi/mayavi/auto/example_wx_embedding.html) fails for me.
`NotImplementedError: the null tvtk.pyface.ui.null backend doesn't implement scene_editor:SceneEditor`

**Comment by corranwebster** [comment]
The most recent release of TraitsUI does not support wxPython 4.

There is experimental support in master of TraitsUI for wxPython 4, but there are known issues with it.  If this is important for your use-case, any help you can provide to debug and/or fix would be welcome.

**Comment by corranwebster** [comment]
wxPython 4 support has been released with TraitsUI 7.  This should resolve this issue.
