### ISSUE TITLE
Replace use of traits_view trait with default_traits_view method

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#788]
A future release of `traits` will warn about any redefinition of traits/methods with a prefix `trait` or `_trait`, see this issue: https://github.com/enthought/traits/issues/705

Currently `traits_view` has been used various places in `traitsui` and have been mentioned in the user documentation as a way to provide the default view.

One can easily switch to overriding the `default_traits_view` method to avoid this warning.

**Comment by corranwebster** [comment]
I think a distinction needs to be made between defining a `traits_view()` _method_ which returns a `View` and saying `traits_view = View(...)`.  The former is problematic, the latter is fine (but should also not trigger warnings since the attribute gets removed from class by the metaclass).  

I believe the documentation about `traits_view` is referring to the latter, not the former.

**Comment by kitchoi** [comment]
I agree that the documentation is about defining the `traits_view` trait, as in here:
https://github.com/enthought/traitsui/blob/148457a08b4f0fc14ccff6dc2166fa8f0251643c/examples/tutorials/doc_examples/examples/default_traits_view.py#L14-L27

A future release `traits` will warn about this as far as I can tell.

**Comment by corranwebster** [comment]
`traits_view` isn't a trait, it's a View.  It gets special-cased:

https://github.com/enthought/traits/blob/master/traits/has_traits.py#L502-L507

So `traits_view` (and indeed, any other `View`) gets removed from the class dict and tucked away into `__view_elements__` and so doesn't shadow any `traits_*` methods.

**Comment by kitchoi** [comment]
🤦 It is like traits fighting itself! 😢

**Comment by kitchoi** [comment]
Perhaps traits should check for name clash *after* these special attributes have been handled.
I will close this one and tackle this in traits instead.
Thank you for looking into this.
