### ISSUE TITLE
Infinite loop in traitsui.extras.demo

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#792]
The tutorial application hangs when choosing an element that has a directory as a previous sibling. E.g. choosing `sibling2` in this tree would freeze the application:
```
parent/
    sibling1/
        leaf.py
    sibling2/
        leaf.py
```
The application hangs because of this infinite loop:
https://github.com/enthought/traitsui/blob/3e2ce8604f8916ac68025c78fdc1985001d9c18b/traitsui/extras/demo.py#L963-L967

**Comment by corranwebster** [comment]
The fix looks like it is simply adding
```
                    previous_children = previous.tno_get_children(previous)
```
after 967.  The algorithm is basically looking for the previous element in a preorder tree traversal.
