### ISSUE TITLE
Demo application HTML view is not getting a base_url

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#804]
This means links to images, etc. aren't working.

**Comment by kitchoi** [comment]
#808 has added the `base_url` to the various `HTMLEditor`.

From #808:
> It doesn't totally fix #804. It should display the image if it is present. It doesn't fix the hard-coded name.

I believe the remaining issue here is that one may get a broken image if the hard-coded "traits_ui_demo.jpg" file does not exist.
