### ISSUE TITLE
test_wrap_text_narrow{,_short} failures in mock

### ISSUE THREAD

**Issue by opoplawski** [enthought/traitsui#812]
Trying to build the Fedora traitsui package for 7.0.0 I'm getting the following test failure when building in mock (the Fedora package buildroot tool):
```
+ xvfb-run /usr/bin/python3 -s -m unittest discover -v
FAIL: test_wrap_text_narrow (traitsui.qt4.tests.test_helper.TestWrapText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/traitsui-7.0.0/traitsui/qt4/tests/test_helper.py", line 88, in test_wrap_text_narrow
    self.assertTrue(all(len(line) <= 21 for line in lines))
AssertionError: False is not true
======================================================================
FAIL: test_wrap_text_narrow_short (traitsui.qt4.tests.test_helper.TestWrapText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/traitsui-7.0.0/traitsui/qt4/tests/test_helper.py", line 103, in test_wrap_text_narrow_short
    self.assertTrue(all(len(line) <= 21 for line in lines))
AssertionError: False is not true
----------------------------------------------------------------------
```
I'm not able to reproduce the failure locally on my machine.  I thought in might be a difference with LANG settings, but setting LANG=C.UTF-8 (which is what is used in mock) doesn't seem to trigger it.  Any other thoughts?

**Comment by corranwebster** [comment]
It could be related to font availability.  We also had test failures for this test on *BSD systems where the ellipsis `…` was replaced with three periods `...`, so it could have to do with unicode support (but the tests were fixed to allow that particular case).

It might also be due to differenced in the underlying rendering system, so it may be that the width needs to be tweaked a pixel or two on some systems (IIRC that test is trying to render into a 20px wide box).

**Comment by opoplawski** [comment]
Looks like the only fonts that get installed by default are google-noto-sans-vf-fonts:
```
/usr/share/fonts/google-noto-vf/NotoSans-Italic-VF.ttf
/usr/share/fonts/google-noto-vf/NotoSans-VF.ttf
```
Is there a recommended set of fonts to test with?

**Comment by opoplawski** [comment]
Near as I can tell the `ETS from source` action doesn't get any fonts installed - but that seems unlikely to allow tests to succeed.

**Comment by opoplawski** [comment]
Finally sorted it out by installing the dejavu and liberation fonts (which are installed in the Ubuntu test image)
