### ISSUE TITLE
Demo app sometimes freezes when clicking on folder name

### ISSUE THREAD

**Issue by achabotl** [enthought/traitsui#824]
The new version of the Demo app sometimes freeze when clicking directly on a folder name on macOS.

To reproduce:

1. `python demo.py`
2. Click on Advanced folder (no freezing)
3. Click on Applications folder (freezes)

Force quit, restart app;

1. Click on disclosure triangle next to Applications (doesn't freeze)
2. Click on script name (everything is fine).
3. Click on Applications folder (freezes)

I thought it was because `Applications/__init__.py` was empty, but if tried putting the `__init__.py` from Advanced into Applications and it didn't prevent freezing.

## Versions and platform:

macOS 10.15.4 (19E287)

```
# Packages in environment 'tmptui'
#  prefix: '/Users/achabot/.edm/envs/tmptui'
appdirs            1.4.3-1   enthought/free
configobj          5.0.6-3   enthought/free
distribute_remove  1.0.0-4   enthought/free
icu4c              50.2-2    enthought/free
libjpeg            7.0-5     enthought/free
libpng             1.6.36-3  enthought/free
packaging          16.8-3    enthought/free
pip                20.0.2-1  enthought/free
pyface             7.0.0-1   enthought/free
pygments           2.2.0-1   enthought/free
pyparsing          2.2.0-1   enthought/free
pyqt5              5.7.1-2   enthought/free
qt                 5.6.2-5   enthought/free
setuptools         41.6.0-3  enthought/free
sip                4.19.2-2  enthought/free
six                1.11.0-1  enthought/free
traits             6.0.0-1   enthought/free
traitsui           7.0.0-1   enthought/free

```

**Comment by corranwebster** [comment]
I _think_ this was fixed in #799, and #808 (which is pending) fixes a number of other errors and issues.  If you are going to play with the Demo app, use that branch for now.
