### ISSUE TITLE
Run CI with EDM PyQt 5.14 and Qt 5.12

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#831]
These have just been released in EDM.  We should switch CI to use these where possible.

Qt 5.12 is a reasonable baseline that we should expect tests to pass on.

**Comment by mdickinson** [comment]
Doesn't this happen automatically? I don't think we're specifying a particular version of PyQt5 in `etstool.py` - we're just picking up the latest that EDM has to offer.

**Comment by corranwebster** [comment]
Yes, you're probably right - I'm so used to pinning versions of the pip deployed ones.  I'll leave the issue open until we actually get a successful test run, however :)

**Comment by kitchoi** [comment]
While we are at this, let's put the PyQt4 and PySide back to CI following https://github.com/enthought/pyface/pull/519
If not, then a separate issue for putting them back will be needed.

**Comment by kitchoi** [comment]
> While we are at this, let's put the PyQt4 and PySide back to CI following enthought/pyface#519
If not, then a separate issue for putting them back will be needed.

Sorry, there is already one: #821

**Comment by ievacerny** [comment]
I checked and CI is automatically running on PyQt 5.14 and Qt 5.12. Here's a link to a successful run from the latest merged PR: https://travis-ci.org/github/enthought/traitsui/builds/699641048

I think that closes the issue or is there something else regarding enthought/pyface#519?
