### ISSUE TITLE
Linux qt test interactions: remaining connection to old ImageEnumModel instance

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#854]
I've been seeing some test interactions where `data` method of an old `ImageEnumModel` instance is called in a different test (and fails because `self._editor.factory` is `None`) https://travis-ci.org/github/enthought/traitsui/jobs/692588809

I don't know what exactly isn't being cleaned up and what is the exact connection that remains. I'm failing to reproduce this locally on a Linux VM so I can't debug this any further, but it's happening consistently on Linux CI.

Just for reference, there is a similar issue for wx test interactions on windows (https://github.com/enthought/traitsui/issues/851)

**Comment by kitchoi** [comment]
Thank you for the issue!

Here is the test failure just in case Travis-CI causes us to lose the log:
```
======================================================================
ERROR: test_simple_editor_more_cols (traitsui.tests.editors.test_image_enum_editor.TestSimpleImageEnumEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/.edm/envs/traitsui-test-3.6-pyside2/lib/python3.6/site-packages/traitsui/tests/editors/test_image_enum_editor.py", line 314, in test_simple_editor_more_cols
    self.setup_gui(enum_edit, view)
  File "/home/travis/.edm/envs/traitsui-test-3.6-pyside2/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/travis/.edm/envs/traitsui-test-3.6-pyside2/lib/python3.6/site-packages/traitsui/tests/_tools.py", line 66, in store_exceptions_on_all_threads
    raise exceptions[0]
  File "/home/travis/.edm/envs/traitsui-test-3.6-pyside2/lib/python3.6/site-packages/traitsui/qt4/image_enum_editor.py", line 301, in data
    index = mi.row() * self._editor.factory.cols + mi.column()
AttributeError: 'NoneType' object has no attribute 'cols'
```
(Job was run on this commit: 0620721122f7767bf43ea512b9f4e738753bab6b)

**Comment by kitchoi** [comment]
FTR, this [commit](https://github.com/enthought/traitsui/pull/865/commits/7466c03f9cabb377d63ea59845224d0a111312cb) tries to remove the skips after ensuring all `UI.dispose` are called in other tests (assuming I had got that right). That did not help with this issue.

**Comment by ievacerny** [comment]
I don't think it's any other tests that are causing the issue. I think the issue is with all tests in `test_image_enum_editor.py` that create a simple `ImageEnumEditor`. The editor is not garbage collected at the end for some reason and that causes the following test to fail.

**Comment by ievacerny** [comment]
Tests for `ListStrEditor` were failing in a similar way with pyside2, but they were failing on Mac and Windows instead of Linux. I could replicate the errors locally and I found two ways to get rid of them:
1. Adding `toolkit.destroy_control(self.control)` to the `dispose` method of the editor.
2. Not modifying the editor but adding `gui.process_events()` to a test that wasn't really doing anything apart from editor initialisation

I found this pretty much by trial and error, so I don't actually know why either of the methods work. Dumping my findings here in case they might be useful in investigating this issues.

**Comment by kitchoi** [comment]
> Adding toolkit.destroy_control(self.control) to the dispose method of the editor.

This was done in this PR a long time ago for avoiding the attribute error, by this PR 9 years ago https://github.com/enthought/traitsui/pull/46
But then that is reversed in this PR: https://github.com/enthought/traitsui/pull/283
Looks like we should not go back on that cycle again...

This is my current understanding of the issue:
(1) After the UI is initialized, actions in the test cause some events are posted onto the event queue. We call `processEvents` to get the changes we want to assert.
(2) `QtCore.QCoreApplication.processEvents` only processes the events that have been posted when the function is called. Any new events posted by processing those events are not processed. Hence calling `GUI.process_events()` only actually makes the GUI event queue empty if the posted events do not cause a cascade of new events. For more complicated UI, like a table editor, it is very likely that we will get a cascade of events.
(3) Consequently, it is possible to post events to be left unprocessed on the event queues prior to `UI.dispose` is called.
(4) `UI.dispose` removes references to the `control`, `factory`, and friends in the editor by setting them to `None`.
(5) Then when the GUI event queue is processed again, maybe by the same test and the next test, the posted events are processed and they are accessing attributes on `None`, hence the `AttributeError`.

This concerns tearing down TraitsUI editors and UI in tests. Hence it makes sense for the fix to only live in the test world.

The solution would be to process all the events in the event queue *until no events are left on the event queue*, prior to calling `UI.dispose`.

In wx world, this can be done easily by calling `pyface.api.GUI.process_events()` once. In fact, I could not find a way to only process the current snapshot of events in wx.

In Qt world, as mentioned above, `pyface.api.GUI.process_events()` does not necessarily empty the event queue. We may be able to use the overloaded signature of `processEvents`: https://doc.qt.io/qt-5/qcoreapplication.html#processEvents-1, which says "Processes pending events for the calling thread for ms milliseconds or until there are no more events to process, whichever is shorter". As a preliminary experimentation, this fix works with PySide2 but not PyQt5, but I might be doing something stupid.
