### ISSUE TITLE
Extract Demo App into an independently deployable package

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#904]
Currently the demo application is tied to the deployment of TraitsUI. Since TraitsUI is a library heavily depended on by other packages, it needs to be stable and should have fewer external dependencies. On the other hand, the demo application, um, is an application which can be developed and deployed more frequently and maybe with more external dependencies. The latter is more achievable if it is decoupled from TraitsUI.

**Comment by corranwebster** [comment]
I think an approach which might work (at least initially) is to create a new package for the examples (ie. with its own setup.py, dependencies, etc.) that can be pip installed and uploaded to PyPI, but which is also part of this repo so that it stays in sync with TraitsUI.

**Comment by kitchoi** [comment]
- We will keep the demo.py in the same git repository, but have a separate folder with setup.py
- We will keep the `traitsui.extras.demo` importable by other packages e.g. traits
- TraitsUI example should be shown as the default, maybe by hard-coding it.

**Comment by kitchoi** [comment]
> TraitsUI example should be shown as the default, maybe by hard-coding it.

My understanding of this is that the independently deployed application will still show TraitsUI's demo examples. That isn't possible because TraitsUI examples are only available from the source distribution.
