### ISSUE TITLE
Crash when using UI.dispose() with a TableEditor nested in a ListEditor

### ISSUE THREAD

**Issue by xamcost** [enthought/traitsui#907]
Hi there !

I ran into a python crash upon calling `traitsui.ui.UI.dispose()`, which happens when a `ListEditor` is using to display a list of `HasTraits` objects featuring a view using `TableEditor`. This occurs with qt4 and qt5. I used traits 6.0 and traitsui 7. The snippet below reproduces this crash:

```Python3
from traits.api import List, HasTraits, Str
from traitsui.api import ListEditor, TableEditor, UItem, View
from traitsui.table_column import ObjectColumn


class Row(HasTraits):
    col_ = Str()


class ViewWithTableEditor(HasTraits):

    table = List([Row(col_0="1")])

    def traits_view(self):
        view = View(
            UItem(
                'table',
                editor=TableEditor(
                    columns=[ObjectColumn(name='col_0')],
                )
            )
        )
        return view


class MainView(HasTraits):

    tabs = List([ViewWithTableEditor(), ViewWithTableEditor()])

    def traits_view(self):
        view = View(
                UItem('tabs',
                      editor=ListEditor(
                          use_notebook=True,
                      ),
                      style='custom'),
            )
        return view


view = MainView()
ui = view.edit_traits()
ui.dispose()
```
It leads to the following error message:

```
Traceback (most recent call last):
  File "/.edm/envs/msp-dev-3.6/lib/python3.6/site-packages/traitsui/qt4/table_editor.py", line 1059, in resizeEvent
    self.resizeColumnsToContents()
  File "/.edm/envs/msp-dev-3.6/lib/python3.6/site-packages/traitsui/qt4/table_editor.py", line 1176, in resizeColumnsToContents
    width = max(base_width, self.sizeHintForColumn(column_index))
  File "/.edm/envs/msp-dev-3.6/lib/python3.6/site-packages/traitsui/qt4/table_editor.py", line 1127, in sizeHintForColumn
    if editor.factory.sortable and not editor.factory.reorderable:
AttributeError: 'NoneType' object has no attribute 'sortable'
```

Any ideas what is happening ? Thank you in advance for your help !

**Comment by xamcost** [comment]
On another aspect, it is interesting to note that testing an instance of the above `MainView` class with pyface's `GuiTestAssistant` leads to different behaviors depending on the Qt version used. Consider the following code:

```Python3
from unittest import TestCase

from pyface.ui.qt4.util.gui_test_assistant import GuiTestAssistant

class TestImporterViewGui(GuiTestAssistant, TestCase):

    def setUp(self):
        GuiTestAssistant.setUp(self)
        self.view = MainView()
        self.ui = None

    def tearDown(self):
        if self.ui is not None:
            with self.delete_widget(self.ui.control):
                self.ui.dispose()
        self.qt_app.flush()

        del self.ui
        del self.view

        GuiTestAssistant.tearDown(self)

    def test_open_and_close_view(self):
        with self.event_loop():
            self.ui = self.view.edit_traits()
        self.assertGreater(len(self.ui._editors), 0)
```

Whatever version of Qt you use, the raised exception (the `AttributeError` mentioned in my previous post) will remain the same, but the test will fail on qt5, whereas it will pass on qt4.

**Comment by kitchoi** [comment]
Hi @xamcost, yes we are running into these problems as well. #902 and #903 try to address that (the second PR is for testing with CI only and I will eventually close it). The solutions there are not mature yet and I think I would like to see it tested with TraitsUI's own tests first before making it more widely available.

Basically the proposal is those PR is to process all the events *before* calling `dispose`. Note that the `delete_widget` context manager runs the event queue *after* dispose is called, not before.

Unfortunately `QCoreApplication.flush` is deprecated, see https://doc.qt.io/qt-5/qcoreapplication-obsolete.html

**Comment by kitchoi** [comment]
I'm very sorry - I probably should have tried the proposal against your example first before jumping into conclusions. Your error looks *so* similar to what we experienced in other places but simply flushing the event queue before calling `UI.dispose` does not solve it for your case.

**Comment by xamcost** [comment]
No worries ! I am actually very grateful that 1) you answered so fast, and 2) I got to learn more about `UI.dispose()` and `QCoreApplication.flush()` thanks to your explanations and references. I will keep you posted if we get a better understanding of the issue or if we find a workaround.

**Comment by kitchoi** [comment]
I have looked a bit further now... the error looks similar because the reason for the failure is fundamentally the same: There are events posted that have not been processed before `UI.dispose` is called. If I remove this line:
https://github.com/enthought/traitsui/blob/dd26a52c2840ccca250e1787adfe60c43237132f/traitsui/qt4/list_editor.py#L599

Then your example will run without an error. I am just not sure if removing this line is the right thing to do for production where the GUI event loop runs continuously. (There is also another `ui.dispose` in the same editor and which might cause the same error)

**Comment by kitchoi** [comment]
> I will keep you posted if we get a better understanding of the issue or if we find a workaround.

Yes please. Thank you very much!

**Comment by kitchoi** [comment]
This issue has been occupying my mind so I spent a bit more time diving into it and I think I found a satisfying solution.  If you can tolerate a bit of Qt-specific code, calling `ui.control.hide()` before calling `ui.dispose()` should resolve the error. I will come back later (mid next week) to explain more in details what is going on.

**Comment by kitchoi** [comment]
> I will come back later (mid next week) to explain more in details what is going on.

I ended up commenting here (see section "Problems with dispose"): https://github.com/enthought/traitsui/issues/431#issuecomment-648980689

**Comment by xamcost** [comment]
Thank you very much for your investigation and explanations Kit, you solved our problem. Indeed, calling `ui.control.hide()` before `ui.dispose()` works.
