### ISSUE TITLE
Qt TextEditor doesn't always refresh

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#928]
When the value is edited in the handler of a button fire event, `TextEditor` value isn't updated until the focus is set on the editor (clicking on `click_counter` field). The same doesn't seem to happen to the `readonly` editor, but does happen with `simple`, `custom` and `text` style editors.

``` python
class Foo(HasTraits):
    my_button_trait = Button('Click Me')
    click_counter = Int(0)

    def _my_button_trait_fired(self):
        self.click_counter += 1

    traits_view = View(
        'my_button_trait',
        'click_counter',
        buttons=['OK'],
    )
```

**Comment by kitchoi** [comment]
Looks similar to this: https://github.com/enthought/traitsui/issues/913
Any chance you observe this on a Mac OSX too?

**Comment by ievacerny** [comment]
> Any chance you observe this on a Mac OSX too?

Yeah, haven't checked on other platforms

**Comment by xamcost** [comment]
I can confirm this issue is observable on Mac OS X.

**Comment by kitchoi** [comment]
Update: This issue is still valid on current [master](806808f5ab9ab23e2f7fe5e5a874d5e19b200081) 
On OSX 10.15.5 and Python 3.8, these are the dependencies I tested with:
```
Package    Version     
---------- ------------
pip        19.2.3      
pyface     7.0.1       
PySide2    5.15.1      
setuptools 41.2.0      
shiboken2  5.15.1      
traits     6.1.1       
traitsui   7.1.0.dev367
```

**Comment by kitchoi** [comment]
What is interesting is that if I remove the "OK" button, then the issue cannot be reproduced in the same environment:
i.e. instead of
```
    traits_view = View(
        'my_button_trait',
        'click_counter',
        buttons=['OK'],
    )
```

I do:
```
    traits_view = View(
        'my_button_trait',
        'click_counter',
    )
```
Then the textbox is updated as expected.

**Comment by kitchoi** [comment]
Here is some pure PySide2 code that demonstrates the issue.
```
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Form(QDialog):
    def __init__(self, parent=None):
        super(Form, self).__init__(parent)
        self.count = 0

        vlayout = QVBoxLayout()
        self.setLayout(vlayout)

        self.b1 = QPushButton("Button1", parent=self)
        self.b1.clicked.connect(self.button_clicked)
        vlayout.addWidget(self.b1)

        self.textbox = QLineEdit(parent=self)
        self.textbox.setText("0")
        vlayout.addWidget(self.textbox)

        self.setWindowTitle("demo")

        # ---- If this block is removed, then the update would work.
        dialog_button_box = QDialogButtonBox(parent=self)
        self.ok_button = QPushButton("OK")
        dialog_button_box.addButton(self.ok_button, QDialogButtonBox.ActionRole)
        vlayout.addWidget(dialog_button_box)

    def button_clicked(self):
        self.count += 1
        self.textbox.setText(str(self.count))


def main():
    app = QApplication.instance()
    if app is None:
        app = QApplication([])
    ex = Form()
    ex.show()
    app.exec_()

if __name__ == '__main__':
   main()
```

Even if I remove the dialog button box , the rendering is still strange. There is some buffering issue going on:
![Screenshot 2020-10-05 at 13 42 35](https://user-images.githubusercontent.com/3673984/95081034-e2bf6f80-0710-11eb-8327-f6c2982de5e7.png)

The behaviour looks somewhat to this Qt issue: https://bugreports.qt.io/browse/QTBUG-68740

This documented issue on event dispatching on MacOS seems relevant: https://doc.qt.io/qt-5/macos-issues.html#using-native-cocoa-panels

**Comment by kitchoi** [comment]
> Even if I remove the dialog button box , the rendering is still strange.

In fact, I don't even need the QDialogButtonBox. Just adding a second button is enough to make the first button behave strangely.

```
        # ---- If this block is removed, then the update would work.
        self.ok_button = QPushButton("OK")
        vlayout.addWidget(self.ok_button)
```
