### ISSUE TITLE
editable:False + multi_select:True = segfault with TabularEditor and PyQt5

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#930]
The script below causes a Segmentation fault crash when the user drags a row in the table. In Windows, it causes the application window to freeze.

Specs:

OS: ubuntu 18, windows 10)
Python: 3.6
traitsui 7.0.0
PyQt5 5.14.2

```python
from traits.api import *
from traitsui.api import *


class Thing(HasTraits):
    x = Float()

    def _x_default(self):
        import random
        return random.random()


class Demo(HasTraits):
    things = List(Instance(Thing))

    def default_traits_view(self):
        return View(
            UItem(
                name='things',
                editor=TabularEditor(
                    multi_select=True,
                    editable=False,
                    adapter=TabularAdapter(
                        columns=[('A number', 'x')]
                    )
                )
            ),
            resizable=True,
            width=400,
        )


demo = Demo(things=[Thing() for _ in range(10)])
demo.configure_traits()
```

**Comment by kitchoi** [comment]
Thank you for the report!
Looks like this issue is fixed on master.  I checked out the commit and am confident that the fix was brought by the combination of  https://github.com/enthought/traitsui/pull/871 and https://github.com/enthought/traitsui/pull/873

**Comment by notmatthancock** [comment]
I confirmed that the script above works as expected with a fresh environment and traitsui pip installed from master. Thanks @kitchoi; I will close this issue.

**Comment by kitchoi** [comment]
Thank you @notmatthancock for verifying!
