### ISSUE TITLE
Enable brings in Traits 6.0 instead of 6.1 into CI environment

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#934]
Enable is a dependency of Chaco, which was added as a test dependency to allow automatic testing of examples. It is used by one example `examples/demo/Useful/demo_group_size.py`.

The easiest "fix" would be to exclude this example from automatic testing.

A proper fix would need to modify installation code in `etstool.py`, and I'm not sure what would be the best way to do that in order to have a consistent set of packages.

**Comment by rahulporuri** [comment]
> A proper fix would need to modify installation code in etstool.py, and I'm not sure what would be the best way to do that in order to have a consistent set of packages.

you might be able to use `edm plumbing install-package` when installing the test packages.

**Comment by kitchoi** [comment]
The requirement of Pandas < 0.24 is holding CI back from the latest of things. The constrain was probably introduced when pandas 0.24 was causing issues.  Luckily the now latest pandas 0.25 is good enough. See #935
