### ISSUE TITLE
WxPython 4.1 CodeEditor demo errors

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#937]
Typing text in code field (using `examples/demo/Standard_Editors/CodeEditor_demo.py`) with WxPython 4.1 throws these errors:
```
Traceback (most recent call last):
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/code_editor.py", line 375, in _style_needed
    self.control.StartStyling(position, stc.STC_INDIC2_MASK)
TypeError: StyledTextCtrl.StartStyling(): too many arguments
```

**Comment by rahulporuri** [comment]
closing as this was duplicated as https://github.com/enthought/traitsui/issues/1535 and fixed in https://github.com/enthought/traitsui/pull/1536
