### ISSUE TITLE
ProgressColumn bars overlapping with PyQt5 and PySide2

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#964]
`ProgressColumn` rendering is broken with PyQt5 and PySide2, but not PyQt4 (precise versioning `PySide2           5.11.0`, `PyQt5             5.14.2; PyQt5-sip         12.7.2; Qt                5.12.6` but not with `PyQt              4.11.4; Qt                4.8.7`). All progress bars are overlapping:  <img src="https://user-images.githubusercontent.com/25366751/86475338-5d58a780-bd3c-11ea-8f78-bde7aeb160f9.png" width=250>
This image is taken from `examples/demo/Advanced/Table_editor_with_progress_column.py`

**Comment by rahulporuri** [comment]
Note that I am unable to reproduce this on windows with pyqt5 or pyside2 + python 3.6 so this seems to be a mac os-specific issue. I haven't checked the status on linux.

**Comment by aaronayres35** [comment]
Looks like this is useful:
https://forum.qt.io/topic/105375/qitemdelegate-for-drawing-progress-bar-working-but-won-t-move-off-origin/6
I changed `traitsui.qt4.extra.progress_renderer.ProgressRenderer` to be:
```
class ProgressRenderer(TableDelegate):
    """ A renderer which displays a progress bar.
    """

    # -------------------------------------------------------------------------
    #  QAbstractItemDelegate interface
    # -------------------------------------------------------------------------

    def paint(self, painter, option, index):
        """ Paint the progressbar. """

        # Get the column and object
        column = index.model()._editor.columns[index.column()]
        obj = index.data(QtCore.Qt.UserRole)

        # set up progress bar options
        progress_bar_option = QtGui.QStyleOptionProgressBar()
        progress_bar_option.rect = option.rect
        progress_bar_option.minimum = column.get_minimum(obj)
        progress_bar_option.maximum = column.get_maximum(obj)
        progress_bar_option.progress = int(column.get_raw_value(obj))
        progress_bar_option.textVisible = column.get_text_visible()
        progress_bar_option.text = column.get_value(obj)

        # Draw it
        style = QtGui.QApplication.instance().style()
        painter.translate(option.rect.left(), option.rect.top())  # THIS LINE WAS ADDED
        style.drawControl(
            QtGui.QStyle.CE_ProgressBar, progress_bar_option, painter
        )
        painter.resetTransform()  # THIS LINE WAS ADDED
```
and everything seems to work as expected.
I do want to be careful about this comment:
"Another option you have is to save the state of the painter before you modify it and then restore it.
That way you don't complete reset the transformation if any other was applied before your translation."
This is probably the _more correct_ way to do this (although I'm not suer practically speaking it makes a difference)
